# Generated by Django 5.1.1 on 2025-05-13 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0003_banco_codigoretencion_conceptobanco_tarjeta'),
        ('ventas', '0002_factura_productos_camiones_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChequeRecibo',
            fields=[
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('estacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fcontrol', models.CharField(blank=True, max_length=22, null=True)),
                ('id_cheque_recibo', models.AutoField(primary_key=True, serialize=False)),
                ('sucursal', models.SmallIntegerField(blank=True, null=True, verbose_name='Sucursal')),
                ('codigo_postal', models.SmallIntegerField(blank=True, null=True, verbose_name='Código Postal')),
                ('numero_cheque_recibo', models.SmallIntegerField(blank=True, null=True, verbose_name='Número')),
                ('cuenta_cheque_recibo', models.SmallIntegerField(blank=True, null=True, verbose_name='Cuenta')),
                ('cuit_cheque_recibo', models.SmallIntegerField(blank=True, null=True, verbose_name='CUIT')),
                ('fecha_cheque1', models.DateField(blank=True, null=True, verbose_name='Fecha 1')),
                ('fecha_cheque2', models.DateField(blank=True, null=True, verbose_name='Fecha 2')),
                ('importe_cheque_recibo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Importe Cheque')),
                ('id_banco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maestros.banco', verbose_name='Banco')),
                ('id_factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.factura', verbose_name='Factura')),
                ('id_user', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Cheque Recibo',
                'verbose_name_plural': 'Cheques Recibo',
                'db_table': 'cheque_recibo',
            },
        ),
        migrations.CreateModel(
            name='DepositoRecibo',
            fields=[
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('estacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fcontrol', models.CharField(blank=True, max_length=22, null=True)),
                ('id_deposito_recibo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_deposito', models.DateField(blank=True, null=True, verbose_name='Fecha Depósito')),
                ('importe_deposito', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Importe Depósito')),
                ('detalle_deposito', models.CharField(blank=True, max_length=20, null=True, verbose_name='Detalle')),
                ('id_banco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maestros.banco', verbose_name='Banco')),
                ('id_concepto_banco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maestros.conceptobanco', verbose_name='Concepto')),
                ('id_factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.factura', verbose_name='Factura')),
                ('id_user', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Depósito Recibo',
                'verbose_name_plural': 'Dépositos Recibo',
                'db_table': 'deposito_recibo',
            },
        ),
        migrations.CreateModel(
            name='DetalleRecibo',
            fields=[
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('estacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fcontrol', models.CharField(blank=True, max_length=22, null=True)),
                ('id_detalle_recibo', models.AutoField(primary_key=True, serialize=False)),
                ('monto_cobrado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Costo')),
                ('observaciones_recibo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Observaciones')),
                ('id_factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.factura', verbose_name='Factura')),
                ('id_user', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Recibo',
                'verbose_name_plural': 'Recibo',
                'db_table': 'detalle_recibo',
            },
        ),
        migrations.CreateModel(
            name='RetencionRecibo',
            fields=[
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('estacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fcontrol', models.CharField(blank=True, max_length=22, null=True)),
                ('id_retencion_recibo', models.AutoField(primary_key=True, serialize=False)),
                ('certificado', models.CharField(blank=True, max_length=20, null=True, verbose_name='Certificado')),
                ('importe_retencion', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Importe Retención')),
                ('fecha_retencion', models.DateField(blank=True, null=True, verbose_name='Fecha Retención')),
                ('id_codigo_retencion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maestros.conceptobanco', verbose_name='Código Retención')),
                ('id_factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.factura', verbose_name='Factura')),
                ('id_user', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Retención Recibo',
                'verbose_name_plural': 'Retenciones Recibo',
                'db_table': 'retencion_recibo',
            },
        ),
        migrations.CreateModel(
            name='TarjetaRecibo',
            fields=[
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('estacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fcontrol', models.CharField(blank=True, max_length=22, null=True)),
                ('id_tarjeta_recibo', models.AutoField(primary_key=True, serialize=False)),
                ('cupon', models.SmallIntegerField(blank=True, null=True, verbose_name='Cupón')),
                ('lote', models.SmallIntegerField(blank=True, null=True, verbose_name='Lote')),
                ('cuotas', models.SmallIntegerField(blank=True, null=True, verbose_name='Cuotas')),
                ('importe_tarjeta', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Importe Tarjeta')),
                ('id_factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.factura', verbose_name='Factura')),
                ('id_tarjeta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maestros.tarjeta', verbose_name='Tarjeta')),
                ('id_user', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Tarjeta Recibo',
                'verbose_name_plural': 'Tarjetas Recibo',
                'db_table': 'tarjeta_recibo',
            },
        ),
    ]
