# Generated by Django 5.1.1 on 2025-05-28 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_detallerecibo_id_factura_cobrada_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chequerecibo',
            old_name='importe_cheque_recibo',
            new_name='importe_cheque',
        ),
    ]
