# Generated by Django 5.1.1 on 2025-05-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_rename_importe_cheque_recibo_chequerecibo_importe_cheque'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='efectivo_recibo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=14, null=True, verbose_name='Efectivo'),
        ),
    ]
