# Generated by Django 5.1.1 on 2024-09-24 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0003_actividad_fecha_registro_actividad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='descripcion_actividad',
            field=models.CharField(max_length=30, verbose_name='Descripción actividad'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='fecha_registro_actividad',
            field=models.DateField(verbose_name='Fecha de registro'),
        ),
    ]
