# Generated by Django 5.1.1 on 2024-09-30 21:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0004_alter_actividad_descripcion_actividad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='id_usuario',
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.provincia', verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='black_list_motivo',
            field=models.BinaryField(max_length=50, verbose_name='Motivo Black List'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='black_list_usuario',
            field=models.CharField(max_length=20, verbose_name='Usuario Black List'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='codigo_postal',
            field=models.CharField(max_length=5, verbose_name='Código Postal'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='condicion_venta',
            field=models.IntegerField(choices=[(1, 'Contado'), (2, 'Cuenta Corriente')], default=True, verbose_name='Condición Venta'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cuit',
            field=models.IntegerField(verbose_name='CUIT'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='domicilio_cliente',
            field=models.CharField(max_length=50, verbose_name='Domicilio Cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email2_cliente',
            field=models.EmailField(max_length=50, verbose_name='Email 2'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email_cliente',
            field=models.EmailField(max_length=50, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fax_cliente',
            field=models.CharField(max_length=15, verbose_name='Fax'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_alta',
            field=models.DateField(verbose_name='Fecha Alta'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_baja',
            field=models.DateField(verbose_name='Fecha de Baja'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name='Fecha Nacimiento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id_actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.actividad', verbose_name='Actividad'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id_localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestros.localidad', verbose_name='Localidad'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id_percepcion_ib',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.tipopercepcionib', verbose_name='Percepción IB'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id_sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.sucursal', verbose_name='Actividad'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id_tipo_documento_identidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.tipodocumentoidentidad', verbose_name='Tipo Doc. Identidad '),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id_tipo_iva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.tipoiva', verbose_name='Tipo de Iva'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id_vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.vendedor', verbose_name='Vendedor'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='mayorista',
            field=models.BooleanField(choices=[(True, 'SI'), (False, 'NO')], default=False, verbose_name='Cliente VIP'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='movil_cliente',
            field=models.CharField(max_length=15, verbose_name='Móvil'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre_cliente',
            field=models.CharField(max_length=50, verbose_name='Nombre Cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero_ib',
            field=models.CharField(max_length=15, verbose_name='Número IB'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='observaciones_cliente',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='sub_cuenta',
            field=models.IntegerField(verbose_name='Sub Cuenta'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono_cliente',
            field=models.CharField(max_length=15, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_persona',
            field=models.CharField(max_length=1, verbose_name='Tipo de Persona'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='transporte_cliente',
            field=models.CharField(max_length=50, verbose_name='Transporte'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='vip',
            field=models.BooleanField(choices=[(True, 'SI'), (False, 'NO')], default=False, verbose_name='Cliente VIP'),
        ),
        migrations.AlterField(
            model_name='comprobantecompra',
            name='codigo_afip_a',
            field=models.CharField(max_length=3, verbose_name='Código AFIP A'),
        ),
        migrations.AlterField(
            model_name='comprobantecompra',
            name='codigo_afip_b',
            field=models.CharField(max_length=3, verbose_name='Código AFIP B'),
        ),
        migrations.AlterField(
            model_name='comprobantecompra',
            name='codigo_afip_c',
            field=models.CharField(max_length=3, verbose_name='Código AFIP C'),
        ),
        migrations.AlterField(
            model_name='comprobantecompra',
            name='codigo_afip_m',
            field=models.CharField(max_length=3, verbose_name='Código AFIP M'),
        ),
        migrations.AlterField(
            model_name='comprobantecompra',
            name='codigo_comprobante_compra',
            field=models.CharField(max_length=3, verbose_name='Código comprobante'),
        ),
        migrations.AlterField(
            model_name='comprobantecompra',
            name='libro_iva',
            field=models.BooleanField(verbose_name='Libreo IVA'),
        ),
        migrations.AlterField(
            model_name='comprobantecompra',
            name='mult_caja',
            field=models.IntegerField(verbose_name='Mult. IVA'),
        ),
        migrations.AlterField(
            model_name='comprobantecompra',
            name='mult_compra',
            field=models.IntegerField(verbose_name='Mult. Compra'),
        ),
        migrations.AlterField(
            model_name='comprobantecompra',
            name='mult_saldo',
            field=models.IntegerField(verbose_name='Mult. Saldo'),
        ),
        migrations.AlterField(
            model_name='comprobantecompra',
            name='mult_stock',
            field=models.IntegerField(verbose_name='Mult. Stock'),
        ),
        migrations.AlterField(
            model_name='comprobantecompra',
            name='nombre_comprobante_compra',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='comprobanteventa',
            name='codigo_afip_a',
            field=models.CharField(max_length=3, verbose_name='Código AFIP A'),
        ),
        migrations.AlterField(
            model_name='comprobanteventa',
            name='codigo_afip_b',
            field=models.CharField(max_length=3, verbose_name='Código AFIP B'),
        ),
        migrations.AlterField(
            model_name='comprobanteventa',
            name='codigo_comprobante_venta',
            field=models.CharField(max_length=3, verbose_name='Código Comprobante'),
        ),
        migrations.AlterField(
            model_name='comprobanteventa',
            name='compro_asociado',
            field=models.CharField(max_length=20, verbose_name='Comprobate Asociado'),
        ),
        migrations.AlterField(
            model_name='comprobanteventa',
            name='electronica',
            field=models.BooleanField(verbose_name='Electrónica'),
        ),
        migrations.AlterField(
            model_name='comprobanteventa',
            name='estadistica',
            field=models.BooleanField(verbose_name='Estadísticas'),
        ),
        migrations.AlterField(
            model_name='comprobanteventa',
            name='impresion',
            field=models.CharField(max_length=50, verbose_name='Impresora'),
        ),
        migrations.AlterField(
            model_name='comprobanteventa',
            name='info_michelin_auto',
            field=models.BooleanField(verbose_name='Info. Michelin auto'),
        ),
        migrations.AlterField(
            model_name='comprobanteventa',
            name='info_michelin_camion',
            field=models.BooleanField(verbose_name='Info. Michelin camión'),
        ),
        migrations.AlterField(
            model_name='comprobanteventa',
            name='libro_iva',
            field=models.BooleanField(verbose_name='Libro IVA'),
        ),
        migrations.AlterField(
            model_name='comprobanteventa',
            name='mult_caja',
            field=models.IntegerField(verbose_name='Mult. Caja'),
        ),
        migrations.AlterField(
            model_name='comprobanteventa',
            name='mult_comision',
            field=models.IntegerField(verbose_name='Mult. Comisión'),
        ),
        migrations.AlterField(
            model_name='comprobanteventa',
            name='mult_estadistica',
            field=models.IntegerField(verbose_name='Mult. Estadísticas'),
        ),
        migrations.AlterField(
            model_name='comprobanteventa',
            name='mult_saldo',
            field=models.IntegerField(verbose_name='Mult. Saldo'),
        ),
        migrations.AlterField(
            model_name='comprobanteventa',
            name='mult_stock',
            field=models.IntegerField(verbose_name='Mult. Stock'),
        ),
        migrations.AlterField(
            model_name='comprobanteventa',
            name='mult_venta',
            field=models.IntegerField(verbose_name='Mult. Venta'),
        ),
        migrations.AlterField(
            model_name='comprobanteventa',
            name='nombre_comprobante_venta',
            field=models.CharField(max_length=50, verbose_name='Nombre Comprobante'),
        ),
        migrations.AlterField(
            model_name='comprobanteventa',
            name='pendiente',
            field=models.BooleanField(verbose_name='Pendiente'),
        ),
        migrations.AlterField(
            model_name='comprobanteventa',
            name='presupuesto',
            field=models.BooleanField(verbose_name='Presupuesto'),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='codigo_postal',
            field=models.CharField(max_length=5, verbose_name='Código Postal'),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='id_provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.provincia', verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='nombre_localidad',
            field=models.CharField(max_length=30, verbose_name='Nombre Localidad'),
        ),
        migrations.AlterField(
            model_name='moneda',
            name='cotizacion_moneda',
            field=models.DecimalField(decimal_places=4, max_digits=18, verbose_name='Cotización'),
        ),
        migrations.AlterField(
            model_name='moneda',
            name='nombre_moneda',
            field=models.CharField(max_length=20, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='moneda',
            name='predeterminada',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Predeterminada'),
        ),
        migrations.AlterField(
            model_name='moneda',
            name='simbolo_moneda',
            field=models.CharField(max_length=3, verbose_name='Símbolo'),
        ),
        migrations.AlterField(
            model_name='moneda',
            name='ws_afip',
            field=models.CharField(max_length=3, verbose_name='WS AFIP'),
        ),
        migrations.AlterField(
            model_name='operario',
            name='email_operario',
            field=models.CharField(max_length=50, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='operario',
            name='nombre_operario',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='operario',
            name='telefono_operario',
            field=models.CharField(max_length=50, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='alicuota_iva',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Alícuota IVA'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cai',
            field=models.CharField(max_length=20, verbose_name='CAI'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='carrito',
            field=models.BooleanField(verbose_name='Carrito'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo_producto',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)], verbose_name='Código producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='costo',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Costo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion_producto',
            field=models.CharField(max_length=50, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descuento',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Descuento'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='despacho_1',
            field=models.CharField(max_length=16, verbose_name='Despacho 1'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='despacho_2',
            field=models.CharField(max_length=16, verbose_name='Despacho 2'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_fabricacion',
            field=models.CharField(max_length=6, verbose_name='Fecha fabricación'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id_familia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.productofamilia', verbose_name='Familia'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id_marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.productomarca', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id_modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.productomodelo', verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='medida',
            field=models.CharField(max_length=15, verbose_name='Medida'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='minimo',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)], verbose_name='Stock mínimo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre_producto',
            field=models.CharField(max_length=50, verbose_name='Nombre producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='segmento',
            field=models.CharField(max_length=3, verbose_name='Segmento'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)], verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_producto',
            field=models.CharField(choices=[('p', 'Producto'), ('S', 'Servicio')], max_length=1, verbose_name='Tipo producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)], verbose_name='Unidad'),
        ),
        migrations.AlterField(
            model_name='productodeposito',
            name='id_sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.sucursal', verbose_name='Sucursal'),
        ),
        migrations.AlterField(
            model_name='productodeposito',
            name='nombre_producto_deposito',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='productoestado',
            name='estado_producto',
            field=models.CharField(max_length=1, verbose_name='Estado Producto'),
        ),
        migrations.AlterField(
            model_name='productoestado',
            name='nombre_producto_estado',
            field=models.CharField(max_length=15, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='productofamilia',
            name='comision_operario',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Comisión Operario'),
        ),
        migrations.AlterField(
            model_name='productofamilia',
            name='nombre_producto_familia',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='productomarca',
            name='id_moneda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestros.moneda', verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='productomarca',
            name='nombre_producto_marca',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='productomarca',
            name='principal',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Principal'),
        ),
        migrations.AlterField(
            model_name='productominimo',
            name='cai',
            field=models.CharField(max_length=20, verbose_name='CAI'),
        ),
        migrations.AlterField(
            model_name='productominimo',
            name='id_deposito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.productodeposito', verbose_name='Depósito'),
        ),
        migrations.AlterField(
            model_name='productominimo',
            name='minimo',
            field=models.IntegerField(verbose_name='Mínimo'),
        ),
        migrations.AlterField(
            model_name='productomodelo',
            name='nombre_modelo',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='productostock',
            name='fecha_producto_stock',
            field=models.DateField(verbose_name='Fecha Stock'),
        ),
        migrations.AlterField(
            model_name='productostock',
            name='id_deposito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.productodeposito', verbose_name='Depósito'),
        ),
        migrations.AlterField(
            model_name='productostock',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.producto', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='productostock',
            name='minimo',
            field=models.IntegerField(verbose_name='Mínimo'),
        ),
        migrations.AlterField(
            model_name='productostock',
            name='stock',
            field=models.IntegerField(verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='codigo_provincia',
            field=models.CharField(max_length=1, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='nombre_provincia',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='tipodocumentoidentidad',
            name='codigo_afip',
            field=models.CharField(max_length=2, verbose_name='Código AFIP'),
        ),
        migrations.AlterField(
            model_name='tipodocumentoidentidad',
            name='nombre_documento_identidad',
            field=models.CharField(max_length=4, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='tipodocumentoidentidad',
            name='tipo_documento_identidad',
            field=models.CharField(max_length=4, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='tipodocumentoidentidad',
            name='ws_afip',
            field=models.CharField(max_length=2, verbose_name='WS AFIP'),
        ),
        migrations.AlterField(
            model_name='tipoiva',
            name='codigo_iva',
            field=models.CharField(max_length=4, verbose_name='Código IVA'),
        ),
        migrations.AlterField(
            model_name='tipoiva',
            name='discrimina_iva',
            field=models.BooleanField(blank=True, null=True, verbose_name='Discrimina IVA'),
        ),
        migrations.AlterField(
            model_name='tipoiva',
            name='nombre_iva',
            field=models.CharField(max_length=25, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='tipopercepcionib',
            name='alicuota',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Alícuota'),
        ),
        migrations.AlterField(
            model_name='tipopercepcionib',
            name='descripcion_tipo_percepcion_ib',
            field=models.CharField(max_length=50, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='tipopercepcionib',
            name='minimo',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Mínimo'),
        ),
        migrations.AlterField(
            model_name='tipopercepcionib',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='tipopercepcionib',
            name='neto_total',
            field=models.BooleanField(blank=True, null=True, verbose_name='Neto total'),
        ),
        migrations.AlterField(
            model_name='tiporetencionib',
            name='alicuota_inscripto',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Alícuota Inscripto'),
        ),
        migrations.AlterField(
            model_name='tiporetencionib',
            name='alicuota_no_inscripto',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Alícuota No Inscripto'),
        ),
        migrations.AlterField(
            model_name='tiporetencionib',
            name='descripcion_tipo_retencion_ib',
            field=models.CharField(max_length=50, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='tiporetencionib',
            name='minimo',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Mínimo'),
        ),
        migrations.AlterField(
            model_name='tiporetencionib',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Monto'),
        ),
    ]
