# Generated by Django 5.1.1 on 2024-10-01 22:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0005_remove_cliente_id_usuario_cliente_id_provincia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametro',
            name='bonificacion',
        ),
        migrations.RemoveField(
            model_name='parametro',
            name='cierreventas',
        ),
        migrations.RemoveField(
            model_name='parametro',
            name='descripcion_parametro',
        ),
        migrations.RemoveField(
            model_name='parametro',
            name='dolar',
        ),
        migrations.RemoveField(
            model_name='parametro',
            name='precios',
        ),
        migrations.AddField(
            model_name='parametro',
            name='cotizacion_dolar',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=18, verbose_name='Cotización Dólar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parametro',
            name='descuento_maximo',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=6, verbose_name='Intereses Dólar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parametro',
            name='dias_vencimiento',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)], verbose_name='Días Vcto.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parametro',
            name='interes_dolar',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='Intereses Dólar'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parametro',
            name='id_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='interes',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Intereses'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='codigo_postal',
            field=models.CharField(max_length=5, verbose_name='Código postal'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='cuit',
            field=models.BigIntegerField(verbose_name='C.U.I.T.'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='domicilio_proveedor',
            field=models.CharField(max_length=50, verbose_name='Domicilio'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='email_proveedor',
            field=models.EmailField(max_length=50, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='ib_alicuota',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Alíc. Ing. B.'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='ib_exento',
            field=models.BooleanField(verbose_name='Exento Ret. Ing. Bruto'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='ib_numero',
            field=models.CharField(max_length=15, verbose_name='Ingreso Bruto*'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='id_localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.localidad', verbose_name='Localidad'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='id_tipo_iva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.tipoiva', verbose_name='Tipo IVA'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='id_tipo_retencion_ib',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.tiporetencionib', verbose_name='Tipo de Retención Ib'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='movil_proveedor',
            field=models.CharField(max_length=15, verbose_name='Móvil'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='multilateral',
            field=models.BooleanField(verbose_name='Contrib. Conv. Multilateral'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre_proveedor',
            field=models.CharField(max_length=50, verbose_name='Nombre proveedor'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='observacion_proveedor',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono_proveedor',
            field=models.CharField(max_length=15, verbose_name='Taléfono'),
        ),
    ]
