# Generated by Django 5.1.1 on 2024-10-03 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0008_alter_cliente_black_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='mayorista',
            field=models.BooleanField(choices=[(True, 'SI'), (False, 'NO')], default=False, verbose_name='Mayorista'),
        ),
    ]
