# Generated by Django 5.1.1 on 2025-01-03 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VLSaldosClientes',
        ),
    ]
