CLOSE DATABASES
CLEAR ALL
CLEAR 

USE FACTURAS IN 0 ORDER ID
USE DETVEN IN 0
USE STOCKCLIENTE IN 0

USE DESKTOP\FACTURAS IN 0 ALIAS FACTOLD ORDER ID
USE DESKTOP\DETVEN IN 0 ALIAS DETVEOLD ORDER ID

* depuracion de la tabla stockcliente
SELECT STOCKCLIENTE
DELETE FOR fecha <= {^2024-01-01} and (cantidad = retirado)
PACK
GO TOP
nofind = 0
nofind2 = 0
DO WHILE !EOF()
	SCATTER MEMVAR
	
	SELECT FACTURAS
	SEEK m.id
	IF !FOUND()
		nofind = nofind + 1
		
		SELECT FACTOLD
		SEEK m.id
		IF !FOUND()
			nofind2 = nofind2 + 1
			? m.ID
		ELSE
			* INSERTAR EN LA TABLA FACTURAS
			SELECT FACTOLD
			SCATTER MEMVAR
			INSERT INTO FACTURAS FROM MEMVAR
			
			* INSERTAR EN LA TABLA DETVEN
			SELECT DETVEOLD
			SET KEY TO m.ID
			GO TOP
			SCAN
				SCATTER MEMVAR
				INSERT INTO DETVEN FROM MEMVAR
			ENDSCAN
			
		ENDIF
	
	ENDIF

	SELECT STOCKCLIENTE
	IF !EOF()
		SKIP
	ENDIF
ENDDO

? '--------------'
? 'No encontrados'
? nofind
? '--------------'
? 'No encontrados 2'
? nofind2

CLOSE DATABASES
CLEAR ALL
