BEGIN TRANSACTION;
INSERT INTO "menu_menuitem" VALUES (1,'Comunes','','','',1,3,1,NULL);
INSERT INTO "menu_menuitem" VALUES (2,'Clientes','cliente_list','','',0,0,NULL,135);
INSERT INTO "menu_menuitem" VALUES (3,'Proveedores','proveedor_list','','',0,1,NULL,137);
INSERT INTO "menu_menuitem" VALUES (4,'Productos','producto_list','','',0,1,NULL,136);
INSERT INTO "menu_menuitem" VALUES (5,'Vendedores','vendedor_list','','',0,3,NULL,135);
INSERT INTO "menu_menuitem" VALUES (6,'Empresa','empresa_list','','',0,4,NULL,1);
INSERT INTO "menu_menuitem" VALUES (7,'Sucursales','sucursal_list','','',0,5,NULL,1);
INSERT INTO "menu_menuitem" VALUES (8,'Números','numero_list','','',0,6,NULL,135);
INSERT INTO "menu_menuitem" VALUES (9,'Bancos','','','',1,4,1,NULL);
INSERT INTO "menu_menuitem" VALUES (10,'Actividad','actividad_list','','',0,0,NULL,1);
INSERT INTO "menu_menuitem" VALUES (11,'Depósitos','producto_deposito_list','','',0,9,NULL,136);
INSERT INTO "menu_menuitem" VALUES (12,'Familias','producto_familia_list','','',0,2,NULL,136);
INSERT INTO "menu_menuitem" VALUES (13,'Marca','producto_marca_list','','',0,3,NULL,136);
INSERT INTO "menu_menuitem" VALUES (14,'Modelos','producto_modelo_list','','',0,4,NULL,136);
INSERT INTO "menu_menuitem" VALUES (15,'CAI','producto_cai_list','','',0,5,NULL,136);
INSERT INTO "menu_menuitem" VALUES (16,'Estados Productos','producto_estado_list','','',0,6,NULL,136);
INSERT INTO "menu_menuitem" VALUES (17,'Estados de Productos por Medidas','medidas_estados_list','','',0,7,NULL,136);
INSERT INTO "menu_menuitem" VALUES (18,'Comprobantes de Ventas','comprobante_venta_list','','',0,8,NULL,135);
INSERT INTO "menu_menuitem" VALUES (19,'Comprobantes de Compras','comprobante_compra_list','','',0,9,NULL,137);
INSERT INTO "menu_menuitem" VALUES (20,'Monedas','moneda_list','','',0,10,NULL,1);
INSERT INTO "menu_menuitem" VALUES (21,'Provincias','provincia_list','','',0,11,NULL,1);
INSERT INTO "menu_menuitem" VALUES (22,'Localidades','localidad_list','','',0,12,NULL,1);
INSERT INTO "menu_menuitem" VALUES (23,'Tipo Documento','tipo_documento_identidad_list','','',0,13,NULL,1);
INSERT INTO "menu_menuitem" VALUES (24,'Tipo IVA','tipo_iva_list','','',0,14,NULL,1);
INSERT INTO "menu_menuitem" VALUES (25,'Alícuotas IVA','alicuota_iva_list','','',0,15,NULL,1);
INSERT INTO "menu_menuitem" VALUES (26,'Tipo Percepción','tipo_percepcion_ib_list','','',0,16,NULL,1);
INSERT INTO "menu_menuitem" VALUES (27,'Tipo Retención','tipo_retencion_ib_list','','',0,17,NULL,1);
INSERT INTO "menu_menuitem" VALUES (28,'Operarios','operario_list','','',0,18,NULL,135);
INSERT INTO "menu_menuitem" VALUES (29,'Medios de Pagos','medio_pago_list','','',0,19,NULL,135);
INSERT INTO "menu_menuitem" VALUES (30,'Puntos de Venta','punto_venta_list','','',0,20,NULL,135);
INSERT INTO "menu_menuitem" VALUES (31,'Bancos Nacionales','banco_list','','',0,21,NULL,9);
INSERT INTO "menu_menuitem" VALUES (32,'Cuentas de Bancos','cuenta_banco_list','','',0,22,NULL,9);
INSERT INTO "menu_menuitem" VALUES (33,'Tarjetas','tarjeta_list','','',0,23,NULL,9);
INSERT INTO "menu_menuitem" VALUES (34,'Códigos de Retención','codigo_retencion_list','','',0,24,NULL,1);
INSERT INTO "menu_menuitem" VALUES (35,'Conceptos de Bancos','concepto_banco_list','','',0,25,NULL,9);
INSERT INTO "menu_menuitem" VALUES (36,'Marketins Origen','marketing_origen_list','','',0,26,NULL,135);
INSERT INTO "menu_menuitem" VALUES (37,'Comprobante Electrónico','factura_list','','',0,0,2,NULL);
INSERT INTO "menu_menuitem" VALUES (38,'Comprobante Manual','factura_manual_list','','',0,1,2,NULL);
INSERT INTO "menu_menuitem" VALUES (39,'Recibo','recibo_list','','',0,2,2,NULL);
INSERT INTO "menu_menuitem" VALUES (40,'Presupuesto','presupuesto_list','','',0,3,2,NULL);
INSERT INTO "menu_menuitem" VALUES (41,'Movimiento Interno','movimiento_interno_list','','',0,4,2,NULL);
INSERT INTO "menu_menuitem" VALUES (42,'Remitos','compra_list','','',0,0,3,NULL);
INSERT INTO "menu_menuitem" VALUES (43,'Retenciones','compra_retencion_list','','',0,1,3,NULL);
INSERT INTO "menu_menuitem" VALUES (44,'Comunes','','','',1,4,4,NULL);
INSERT INTO "menu_menuitem" VALUES (45,'Clientes','cliente_informe_list','','',0,0,NULL,80);
INSERT INTO "menu_menuitem" VALUES (47,'Productos','producto_informe_list','','',0,0,NULL,53);
INSERT INTO "menu_menuitem" VALUES (48,'Vendedores','vendedor_informe_list','','',0,4,NULL,80);
INSERT INTO "menu_menuitem" VALUES (49,'Empresa','','','',0,4,NULL,44);
INSERT INTO "menu_menuitem" VALUES (50,'Sucursales','sucursal_informe_list','','',0,5,NULL,44);
INSERT INTO "menu_menuitem" VALUES (51,'Parámetros','','','',0,6,NULL,44);
INSERT INTO "menu_menuitem" VALUES (52,'Números','','','',0,20,NULL,80);
INSERT INTO "menu_menuitem" VALUES (53,'Productos','','','',1,2,4,NULL);
INSERT INTO "menu_menuitem" VALUES (54,'Actividades','actividad_informe_list','','',0,0,NULL,44);
INSERT INTO "menu_menuitem" VALUES (55,'Depósitos','productodeposito_informe_list','','',0,8,NULL,53);
INSERT INTO "menu_menuitem" VALUES (56,'Familias','productofamilia_informe_list','','',0,3,NULL,53);
INSERT INTO "menu_menuitem" VALUES (57,'Marcas','productomarca_informe_list','','',0,4,NULL,53);
INSERT INTO "menu_menuitem" VALUES (58,'Modelos','productomodelo_informe_list','','',0,5,NULL,53);
INSERT INTO "menu_menuitem" VALUES (59,'CAIs','productocai_informe_list','','',0,6,NULL,53);
INSERT INTO "menu_menuitem" VALUES (60,'Estados','productoestado_informe_list','','',0,7,NULL,53);
INSERT INTO "menu_menuitem" VALUES (61,'Comprobantes Ventas','comprobanteventa_informe_list','','',0,19,NULL,80);
INSERT INTO "menu_menuitem" VALUES (63,'Monedas','moneda_informe_list','','',0,9,NULL,44);
INSERT INTO "menu_menuitem" VALUES (64,'Provincias','provincia_informe_list','','',0,10,NULL,44);
INSERT INTO "menu_menuitem" VALUES (65,'Localidades','localidad_informe_list','','',0,11,NULL,44);
INSERT INTO "menu_menuitem" VALUES (66,'Tipos Documento','tipodocumentoidentidad_informe_list','','',0,12,NULL,44);
INSERT INTO "menu_menuitem" VALUES (67,'Tipos Iva','tipoiva_informe_list','','',0,13,NULL,44);
INSERT INTO "menu_menuitem" VALUES (68,'Alícuotas IVA','alicuotaiva_informe_list','','',0,14,NULL,44);
INSERT INTO "menu_menuitem" VALUES (69,'Tipos Percepción','tipopercepcionib_informe_list','','',0,15,NULL,44);
INSERT INTO "menu_menuitem" VALUES (70,'Tipos Retención','tiporetencionib_informe_list','','',0,16,NULL,44);
INSERT INTO "menu_menuitem" VALUES (71,'Operarios','operario_informe_list','','',0,22,NULL,80);
INSERT INTO "menu_menuitem" VALUES (72,'Medios de Pago','mediopago_informe_list','','',0,23,NULL,80);
INSERT INTO "menu_menuitem" VALUES (73,'Puntos de Venta','puntoventa_informe_list','','',0,24,NULL,80);
INSERT INTO "menu_menuitem" VALUES (74,'Bancos','banco_informe_list','','',0,20,NULL,140);
INSERT INTO "menu_menuitem" VALUES (75,'Cuentas de Bancos','cuentabanco_informe_list','','',0,21,NULL,140);
INSERT INTO "menu_menuitem" VALUES (76,'Tarjetas','tarjeta_informe_list','','',0,22,NULL,140);
INSERT INTO "menu_menuitem" VALUES (77,'Códigos de Retención','codigoretencion_informe_list','','',0,23,NULL,44);
INSERT INTO "menu_menuitem" VALUES (78,'Conceptos de Banco','conceptobanco_informe_list','','',0,24,NULL,140);
INSERT INTO "menu_menuitem" VALUES (79,'Marketing Origen','marketingorigen_informe_list','','',0,25,NULL,80);
INSERT INTO "menu_menuitem" VALUES (80,'Ventas','','','',1,1,4,NULL);
INSERT INTO "menu_menuitem" VALUES (81,'Saldos de Clientes','vlsaldosclientes_informe_list','','',0,1,NULL,80);
INSERT INTO "menu_menuitem" VALUES (82,'Resumen de Cuenta Corriente','vlresumenctacte_informe_list','','',0,2,NULL,80);
INSERT INTO "menu_menuitem" VALUES (83,'Mercadería por Cliente','vlmercaderiaporcliente_informe_list','','',0,3,NULL,80);
INSERT INTO "menu_menuitem" VALUES (84,'Remitos por Cliente','vlremitosclientes_informe_list','','',0,5,NULL,80);
INSERT INTO "menu_menuitem" VALUES (85,'Totales de Remitos por Cliente','vltotalremitosclientes_informe_list','','',0,6,NULL,80);
INSERT INTO "menu_menuitem" VALUES (86,'Comprobantes de Ventas por Localidad','vlventacomprolocalidad_informe_list','','',0,7,NULL,80);
INSERT INTO "menu_menuitem" VALUES (87,'Ventas por Mostrador','vlventamostrador_informe_list','','',0,8,NULL,80);
INSERT INTO "menu_menuitem" VALUES (88,'Total de Ventas por Comprobantes','vlventacompro_informe_list','','',0,9,NULL,80);
INSERT INTO "menu_menuitem" VALUES (89,'Comprobantes Vencidos','vlcomprobantesvencidos_informe_list','','',0,10,NULL,80);
INSERT INTO "menu_menuitem" VALUES (90,'Remitos Pendientes','vlremitospendientes_informe_list','','',0,11,NULL,80);
INSERT INTO "menu_menuitem" VALUES (91,'Remitos por Vendedor','vlremitosvendedor_informe_list','','',0,12,NULL,80);
INSERT INTO "menu_menuitem" VALUES (92,'Libro I.V.A. Ventas','','','',1,14,NULL,80);
INSERT INTO "menu_menuitem" VALUES (93,'Detallado','vlivaventasfull_informe_list','','',0,0,NULL,92);
INSERT INTO "menu_menuitem" VALUES (94,'Totales por Provincia','vlivaventasprovincias_informe_list','','',0,1,NULL,92);
INSERT INTO "menu_menuitem" VALUES (95,'Totales para SITRIB','vlivaventassitrib_informe_list','','',0,2,NULL,92);
INSERT INTO "menu_menuitem" VALUES (96,'Percepciones por Vendedor','','','',1,15,NULL,80);
INSERT INTO "menu_menuitem" VALUES (97,'Vendedores - Solo Totales','vlpercepibvendedortotales_informe_list','','',0,0,NULL,96);
INSERT INTO "menu_menuitem" VALUES (98,'Vendedores - Detallado por Comprobantes','vlpercepibvendedordetallado_informe_list','','',0,1,NULL,96);
INSERT INTO "menu_menuitem" VALUES (99,'Sub Cuentas - Solo Totales','vlpercepibsubcuentatotales_informe_list','','',0,2,NULL,96);
INSERT INTO "menu_menuitem" VALUES (100,'Sub Cuentas - Detallado por Comprobantes','vlpercepibsubcuentadetallado_informe_list','','',0,3,NULL,96);
INSERT INTO "menu_menuitem" VALUES (101,'Comisiones a Vendedores según Facturas','vlcomisionvendedor_informe_list','','',0,17,NULL,80);
INSERT INTO "menu_menuitem" VALUES (102,'Comisiones a Operarios','vlcomisionoperario_informe_list','','',0,18,NULL,80);
INSERT INTO "menu_menuitem" VALUES (103,'Diferencias de Precios en Facturación','vlpreciodiferente_informe_list','','',0,19,NULL,80);
INSERT INTO "menu_menuitem" VALUES (104,'Resumen de Ventas I. Brutos Mercadolibre','vlventasresumenib_informe_list','','',0,13,NULL,80);
INSERT INTO "menu_menuitem" VALUES (106,'Lista de Precios','vllista_informe_list','','',0,1,NULL,53);
INSERT INTO "menu_menuitem" VALUES (107,'Lista de Precios a Revendedores','vllistarevendedor_informe_list','','',0,2,NULL,53);
INSERT INTO "menu_menuitem" VALUES (108,'Listado de Stock por Sucursal','vlstocksucursal_informe_list','','',0,0,NULL,141);
INSERT INTO "menu_menuitem" VALUES (109,'Stock General por Sucursal','vlstockgeneralsucursal_informe_list','','',0,1,NULL,141);
INSERT INTO "menu_menuitem" VALUES (110,'Listado de Stock Único','vlstockunico_informe_list','','',0,2,NULL,141);
INSERT INTO "menu_menuitem" VALUES (111,'Reposición de Stock','vlreposicionstock_informe_list','','',0,3,NULL,141);
INSERT INTO "menu_menuitem" VALUES (112,'Actualizar Productos (Excel)','cargar_excel','proceso=actualizar','',0,0,1,138);
INSERT INTO "menu_menuitem" VALUES (113,'Agregar nuevos Productos (Excel)','cargar_excel','proceso=agregar','',0,1,1,138);
INSERT INTO "menu_menuitem" VALUES (114,'Estadísticas de Ventas','vlestadisticasventas_informe_list','','',0,0,6,NULL);
INSERT INTO "menu_menuitem" VALUES (115,'Estadísticas de Ventas Vendedores','vlestadisticasventasvendedor_informe_list','','',0,1,6,NULL);
INSERT INTO "menu_menuitem" VALUES (116,'Estadísticas de Ventas Vendedores Clientes','vlestadisticasventasvendedorcliente_informe_list','','',0,2,6,NULL);
INSERT INTO "menu_menuitem" VALUES (117,'Ventas de Productos Según Condición','vlestadisticasseguncondicion_informe_list','','',0,3,6,NULL);
INSERT INTO "menu_menuitem" VALUES (118,'Estadísticas de Ventas por Marca','vlestadisticasventasmarca_informe_list','','',0,4,6,NULL);
INSERT INTO "menu_menuitem" VALUES (119,'Estadísticas de Ventas por Marca-Vendedor','vlestadisticasventasmarcavendedor_informe_list','','',0,5,6,NULL);
INSERT INTO "menu_menuitem" VALUES (120,'Estadísticas de Clientes sin Movimiento','vlclienteultimaventa_informe_list','','',0,6,6,NULL);
INSERT INTO "menu_menuitem" VALUES (121,'Estadísticas de Ventas por Provincia','vlestadisticasventasprovincia_informe_list','','',0,7,6,NULL);
INSERT INTO "menu_menuitem" VALUES (122,'Comprobantes sin Estadísticas','vlventasinestadistica_informe_list','','',0,8,6,NULL);
INSERT INTO "menu_menuitem" VALUES (124,'Ventas por Comprobantes','vltabladinamicaventas_informe_list','','',0,0,8,NULL);
INSERT INTO "menu_menuitem" VALUES (125,'Detalle de Ventas por Productos','vltabladinamicadetalleventas_informe_list','','',0,1,8,NULL);
INSERT INTO "menu_menuitem" VALUES (126,'Tablas para Estadísticas','vltabladinamicaestadistica_informe_list','','',0,2,8,NULL);
INSERT INTO "menu_menuitem" VALUES (131,'Movimiento Interno de Stock','vlmovimientointernostock_informe_list','','fas fa-book-open',0,5,NULL,141);
INSERT INTO "menu_menuitem" VALUES (135,'Ventas','','','',1,0,1,NULL);
INSERT INTO "menu_menuitem" VALUES (136,'Productos','','','',1,1,1,NULL);
INSERT INTO "menu_menuitem" VALUES (137,'Compras','','','',1,2,1,NULL);
INSERT INTO "menu_menuitem" VALUES (138,'Actualizaciones','','','',1,10,1,136);
INSERT INTO "menu_menuitem" VALUES (140,'Bancos','','','',1,5,4,NULL);
INSERT INTO "menu_menuitem" VALUES (141,'Stock','','','',1,10,4,53);
INSERT INTO "menu_menuitem" VALUES (142,'Compras','','','',1,0,4,NULL);
INSERT INTO "menu_menuitem" VALUES (143,'Detalle de Compras por Proveedor','vldetallecompraproveedor_informe_list','','',0,2,NULL,142);
INSERT INTO "menu_menuitem" VALUES (144,'Comprobantes Ingresados','vlcompraingresada_informe_list','','',0,3,NULL,142);
INSERT INTO "menu_menuitem" VALUES (145,'Stock por Clientes en Depósitos','vlstockcliente_informe_list','','',0,6,NULL,141);
INSERT INTO "menu_menuitem" VALUES (146,'Stock en Depósitos de Clientes','vlstockdeposito_informe_list','','',0,7,NULL,141);
INSERT INTO "menu_menuitem" VALUES (147,'Ficha de Seguimiento de Stock','vlfichaseguimientostock_informe_list','','',0,4,NULL,141);
INSERT INTO "menu_menuitem" VALUES (148,'Comprobantes de Compra','comprobantecompra_informe_list','','',0,0,NULL,142);
INSERT INTO "menu_menuitem" VALUES (149,'Proveedores','proveedor_informe_list','','',0,1,NULL,142);
INSERT INTO "menu_menuitem" VALUES (150,'Caja','caja_list','','',0,0,9,NULL);
INSERT INTO "menu_menuitem" VALUES (151,'Actualizar Estados de Productos','actualizar_estados_productos','','',0,8,NULL,136);
INSERT INTO "menu_menuitem" VALUES (152,'Actualizar Mínimos por CAI','actualizar_minimo_cargar','','',0,2,NULL,138);
INSERT INTO "menu_menuitem" VALUES (153,'Mínimos por CAI','vlproductominimo_informe_list','','',0,9,NULL,53);
INSERT INTO "menu_menuitem" VALUES (154,'Movimientos de Caja','caja_detalle_list','','',0,1,9,NULL);
INSERT INTO "menu_menuitem" VALUES (155,'Caja','','','',1,6,4,NULL);
INSERT INTO "menu_menuitem" VALUES (156,'Planilla de Caja','planillacaja_informe_list','','',0,0,NULL,155);
INSERT INTO "menu_menuitem" VALUES (157,'Egresos de Caja','egresoscaja_informe_list','','',0,2,NULL,155);
INSERT INTO "menu_menuitem" VALUES (158,'Detalle de Tarjetas Recibidas','tarjetarecibo_informe_list','','',0,3,NULL,155);
INSERT INTO "menu_menuitem" VALUES (159,'Detalle de Cupones por Fechas','cuponesfecha_informe_list','','',0,4,NULL,155);
INSERT INTO "menu_menuitem" VALUES (160,'Detalle de Cheques Recibidos','chequerecibo_informe_list','','',0,5,NULL,155);
INSERT INTO "menu_menuitem" VALUES (161,'Arqueo de Caja','cajaarqueo_informe_list','','',0,1,NULL,155);
INSERT INTO "menu_menuitem" VALUES (162,'Detalle de Comprobantes','detallecomprobantes_informe_list','','',0,7,NULL,155);
INSERT INTO "menu_menuitem" VALUES (163,'Detalle de Cheques por Fecha','chequesfecha_informe_list','','',0,6,NULL,155);
COMMIT;
