BEGIN TRANSACTION;
INSERT INTO "menu_menuheading" VALUES (1,'Archivos',0);
INSERT INTO "menu_menuheading" VALUES (2,'Ventas',1);
INSERT INTO "menu_menuheading" VALUES (3,'Compras',3);
INSERT INTO "menu_menuheading" VALUES (4,'Informes',2);
INSERT INTO "menu_menuheading" VALUES (6,'Estadísticas Ventas',6);
INSERT INTO "menu_menuheading" VALUES (7,'Configurar menú',8);
INSERT INTO "menu_menuheading" VALUES (8,'Tablas Dinamicas',7);
INSERT INTO "menu_menuheading" VALUES (9,'Caja',5);
COMMIT;
