# Generated by Django 5.1.1 on 2025-12-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VLProductoMinimo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_cai_id', models.IntegerField()),
                ('cai', models.CharField(max_length=20)),
                ('id_deposito_id', models.IntegerField()),
                ('nombre_producto_deposito', models.CharField(max_length=50)),
                ('minimo', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Stock Mínimo por CAI',
                'verbose_name_plural': 'Stock Mínimo por CAI',
                'db_table': 'VLProductoMinimo',
                'managed': False,
            },
        ),
    ]
