# Generated by Django 5.1.1 on 2025-08-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VLLista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_producto_id', models.IntegerField()),
                ('id_cai_id', models.IntegerField()),
                ('cai', models.CharField(max_length=20)),
                ('tipo_producto', models.CharField(max_length=1)),
                ('medida', models.CharField(max_length=15)),
                ('segmento', models.CharField(max_length=3)),
                ('unidad', models.IntegerField()),
                ('id_familia_id', models.IntegerField()),
                ('nombre_producto_familia', models.CharField(max_length=50)),
                ('id_modelo_id', models.IntegerField()),
                ('nombre_modelo', models.CharField(max_length=50)),
                ('id_marca_id', models.IntegerField()),
                ('nombre_producto_marca', models.CharField(max_length=50)),
                ('nombre_producto', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=6)),
                ('id_alicuota_iva_id', models.IntegerField()),
                ('alicuota_iva', models.DecimalField(decimal_places=2, max_digits=6)),
                ('minimo', models.IntegerField()),
                ('despacho_1', models.CharField(max_length=16)),
                ('despacho_2', models.CharField(max_length=16)),
                ('fecha_fabricacion', models.CharField(max_length=6)),
            ],
            options={
                'verbose_name': 'Lista de Precios',
                'verbose_name_plural': 'Lista de Precios',
                'db_table': 'VLLista',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VLListaRevendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_familia_id', models.IntegerField()),
                ('nombre_producto_familia', models.CharField(max_length=50)),
                ('id_producto_id', models.IntegerField()),
                ('id_cai_id', models.IntegerField()),
                ('cai', models.CharField(max_length=20)),
                ('medida', models.CharField(max_length=15)),
                ('nombre_producto', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('id_marca_id', models.IntegerField()),
                ('id_modelo_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Lista de Precios a Revendedor',
                'verbose_name_plural': 'Lista de Precios a Revendedor',
                'db_table': 'VLListaRevendedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VLStockSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_familia_id', models.IntegerField()),
                ('nombre_producto_familia', models.CharField(max_length=50)),
                ('id_modelo_id', models.IntegerField()),
                ('nombre_modelo', models.CharField(max_length=50)),
                ('id_marca_id', models.IntegerField()),
                ('nombre_producto_marca', models.CharField(max_length=50)),
                ('id_producto_id', models.IntegerField()),
                ('id_cai_id', models.IntegerField()),
                ('cai', models.CharField(max_length=20)),
                ('medida', models.CharField(max_length=15)),
                ('nombre_producto', models.CharField(max_length=50)),
                ('stock', models.IntegerField()),
                ('costo_inventario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('id_deposito_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Listado de Stock por Sucursal',
                'verbose_name_plural': 'Listado de Stock por Sucursal',
                'db_table': 'VLStockSucursal',
                'managed': False,
            },
        ),
    ]
