# Generated by Django 5.1.1 on 2025-08-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0002_vllista_vllistarevendedor_vlstocksucursal'),
    ]

    operations = [
        migrations.CreateModel(
            name='VLStockFecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_familia_id', models.IntegerField()),
                ('nombre_producto_familia', models.CharField(max_length=50)),
                ('id_modelo_id', models.IntegerField()),
                ('nombre_modelo', models.CharField(max_length=50)),
                ('id_marca_id', models.IntegerField()),
                ('nombre_producto_marca', models.CharField(max_length=50)),
                ('id_producto_id', models.IntegerField()),
                ('id_cai_id', models.IntegerField()),
                ('cai', models.CharField(max_length=20)),
                ('medida', models.CharField(max_length=15)),
                ('nombre_producto', models.CharField(max_length=50)),
                ('stock', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Listado de Stock a Fecha',
                'verbose_name_plural': 'Listado de Stock a Fecha',
                'db_table': 'VLStockFecha',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VLStockGeneralSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_familia_id', models.IntegerField()),
                ('nombre_producto_familia', models.CharField(max_length=50)),
                ('id_modelo_id', models.IntegerField()),
                ('nombre_modelo', models.CharField(max_length=50)),
                ('id_marca_id', models.IntegerField()),
                ('nombre_producto_marca', models.CharField(max_length=50)),
                ('id_producto', models.IntegerField()),
                ('id_cai_id', models.IntegerField()),
                ('cai', models.CharField(max_length=20)),
                ('medida', models.CharField(max_length=15)),
                ('nombre_producto', models.CharField(max_length=50)),
                ('stock', models.IntegerField()),
                ('otras_suc', models.IntegerField()),
                ('stock_total', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Stock General por Sucursal',
                'verbose_name_plural': 'Stock General por Sucursal',
                'db_table': 'VLStockGeneralSucursal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VLStockUnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_familia_id', models.IntegerField()),
                ('nombre_producto_familia', models.CharField(max_length=50)),
                ('id_modelo_id', models.IntegerField()),
                ('nombre_modelo', models.CharField(max_length=50)),
                ('id_marca_id', models.IntegerField()),
                ('nombre_producto_marca', models.CharField(max_length=50)),
                ('id_producto_id', models.IntegerField()),
                ('id_cai_id', models.IntegerField()),
                ('cai', models.CharField(max_length=20)),
                ('medida', models.CharField(max_length=15)),
                ('nombre_producto', models.CharField(max_length=50)),
                ('stock', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Listado de Stock Único',
                'verbose_name_plural': 'Listado de Stock Único',
                'db_table': 'VLStockUnico',
                'managed': False,
            },
        ),
    ]
