# Generated by Django 5.1.1 on 2025-04-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0003_vlcomprobantesvencidos_vlivaventasfull_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VLComisionOperario',
            fields=[
                ('id_factura', models.IntegerField(primary_key=True, serialize=False)),
                ('id_operario_id', models.IntegerField()),
                ('nombre_operario', models.CharField(max_length=50)),
                ('codigo_comprobante_venta', models.CharField(max_length=3)),
                ('letra_comprobante', models.CharField(max_length=1)),
                ('numero_comprobante', models.IntegerField()),
                ('comprobante', models.CharField(max_length=19)),
                ('fecha_comprobante', models.DateField()),
                ('id_producto_id', models.IntegerField()),
                ('nombre_producto_familia', models.CharField(max_length=50)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('comision_operario', models.DecimalField(decimal_places=2, max_digits=5)),
                ('monto_comision', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
            options={
                'verbose_name': 'Comisiones a Operarios',
                'verbose_name_plural': 'Comisiones a Operarios',
                'db_table': 'VLComisionOperario',
                'ordering': ['nombre_operario', 'fecha_comprobante', 'numero_comprobante'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VLComisionVendedor',
            fields=[
                ('id_factura', models.IntegerField(primary_key=True, serialize=False)),
                ('compro', models.CharField(max_length=3)),
                ('letra_comprobante', models.CharField(max_length=1)),
                ('numero_comprobante', models.IntegerField()),
                ('comprobante', models.CharField(max_length=19)),
                ('fecha_comprobante', models.DateField()),
                ('nombre_cliente', models.CharField(max_length=50)),
                ('reventa', models.CharField(max_length=1)),
                ('id_producto_id', models.IntegerField()),
                ('medida', models.CharField(max_length=15)),
                ('nombre_producto_marca', models.CharField(max_length=50)),
                ('nombre_producto_familia', models.CharField(max_length=50)),
                ('gravado', models.DecimalField(decimal_places=2, max_digits=14)),
                ('pje_comision', models.DecimalField(decimal_places=2, max_digits=4)),
                ('comision', models.DecimalField(decimal_places=2, max_digits=14)),
                ('id_vendedor_id', models.IntegerField()),
                ('nombre_vendedor', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Comisión Vendedor',
                'verbose_name_plural': 'Comisión Vendedor',
                'db_table': 'VLComisionVendedor',
                'ordering': ['nombre_vendedor', 'fecha_comprobante', 'numero_comprobante'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VLPrecioDiferente',
            fields=[
                ('id_factura', models.IntegerField(primary_key=True, serialize=False)),
                ('id_vendedor_id', models.IntegerField()),
                ('nombre_vendedor', models.CharField(max_length=30)),
                ('codigo_comprobante_venta', models.CharField(max_length=3)),
                ('letra_comprobante', models.CharField(max_length=1)),
                ('fecha_comprobante', models.DateField()),
                ('numero_comprobante', models.IntegerField()),
                ('comprobante', models.CharField(max_length=19)),
                ('id_cliente_id', models.IntegerField()),
                ('nombre_cliente', models.CharField(max_length=50)),
                ('id_producto_id', models.IntegerField()),
                ('nombre_producto', models.CharField(max_length=50)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=7)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_lista', models.DecimalField(decimal_places=2, max_digits=12)),
                ('diferencia', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=6)),
                ('adicional', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name': 'Diferencias de Precios en Facturación',
                'verbose_name_plural': 'Diferencias de Precios en Facturación',
                'db_table': 'VLPrecioDiferente',
                'ordering': ['nombre_vendedor', 'fecha_comprobante', 'numero_comprobante'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VLVentasResumenIB',
            fields=[
                ('id_factura', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_comprobante', models.DateField()),
                ('gravado', models.DecimalField(decimal_places=2, max_digits=14)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('id_provincia_id', models.IntegerField()),
                ('nombre_provincia', models.CharField(max_length=30)),
                ('suc_imp', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Resumen de Ventas por Provincias',
                'verbose_name_plural': 'Resumen de Ventas por Provincias',
                'db_table': 'VLVentasResumenIB',
                'ordering': ['fecha_comprobante'],
                'managed': False,
            },
        ),
    ]
