# Generated by Django 5.1.1 on 2025-08-21 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0003_vlstockfecha_vlstockgeneralsucursal_vlstockunico'),
    ]

    operations = [
        migrations.CreateModel(
            name='VLReposicionStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_deposito', models.IntegerField()),
                ('nombre_producto_deposito', models.CharField(max_length=50)),
                ('id_familia_id', models.IntegerField()),
                ('nombre_producto_familia', models.CharField(max_length=50)),
                ('id_modelo_id', models.IntegerField()),
                ('nombre_modelo', models.CharField(max_length=50)),
                ('id_marca_id', models.IntegerField()),
                ('nombre_producto_marca', models.CharField(max_length=50)),
                ('id_producto_id', models.IntegerField()),
                ('id_cai_id', models.IntegerField()),
                ('cai', models.CharField(max_length=20)),
                ('medida', models.CharField(max_length=15)),
                ('segmento', models.CharField(max_length=3)),
                ('nombre_producto', models.CharField(max_length=50)),
                ('stock', models.IntegerField()),
                ('minimo', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Reposición de Mercadería',
                'verbose_name_plural': 'Reposición de Mercadería',
                'db_table': 'VLReposicionStock',
                'managed': False,
            },
        ),
    ]
