# Generated by Django 5.1.1 on 2025-04-15 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0004_vlcomisionoperario_vlcomisionvendedor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vlcomisionvendedor',
            options={'managed': False, 'ordering': ['nombre_vendedor', 'fecha_comprobante', 'numero_comprobante'], 'verbose_name': 'Comisión Según Facturación', 'verbose_name_plural': 'Comisión Según Facturación'},
        ),
    ]
