# Generated by Django 5.1.1 on 2025-04-28 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0005_alter_vlcomisionvendedor_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='VLEstadisticasVentas',
            fields=[
                ('id_factura', models.IntegerField(primary_key=True, serialize=False)),
                ('id_producto_id', models.IntegerField()),
                ('cai', models.CharField(max_length=20)),
                ('nombre_producto', models.CharField(max_length=50)),
                ('nombre_producto_familia', models.CharField(max_length=50)),
                ('nombre_modelo', models.CharField(max_length=50)),
                ('nombre_producto_marca', models.CharField(max_length=50)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=7)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fecha_comprobante', models.DateField()),
                ('id_cliente_id', models.IntegerField()),
                ('id_sucursal_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Estadísticas de Ventas',
                'verbose_name_plural': 'Estadísticas de Ventas',
                'db_table': 'VLEstadisticasVentas',
                'managed': False,
            },
        ),
    ]
