# Generated by Django 5.1.1 on 2025-05-23 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0007_vlclienteultimaventa_vlestadisticasseguncondicion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vlclienteultimaventa',
            options={'managed': False, 'verbose_name': 'Estadísticas de Clientes sin Ventas', 'verbose_name_plural': 'Estadísticas de Clientes sin Ventas'},
        ),
        migrations.AlterModelTable(
            name='vlclienteultimaventa',
            table='VLClienteUltimaVenta',
        ),
    ]
