# Generated by Django 5.1.1 on 2025-05-06 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maestros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('estacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fcontrol', models.CharField(blank=True, max_length=22, null=True)),
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('id_orig', models.IntegerField(blank=True, null=True, verbose_name='ID_ORIG')),
                ('estatus_comprobante', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estatus')),
                ('jerarquia', models.CharField(blank=True, max_length=1, null=True, verbose_name='Jerarquía')),
                ('compro', models.CharField(blank=True, max_length=3, null=True, verbose_name='Compro')),
                ('letra_comprobante', models.CharField(blank=True, max_length=1, null=True, verbose_name='Letra')),
                ('numero_comprobante', models.IntegerField(blank=True, null=True, verbose_name='Número')),
                ('comprobante_remito', models.CharField(blank=True, default='', max_length=2, null=True, verbose_name='Comprobante Remito')),
                ('remito', models.CharField(blank=True, max_length=15, null=True, verbose_name='Remito')),
                ('fecha_comprobante', models.DateField(blank=True, null=True, verbose_name='Fecha Emisión')),
                ('cuit', models.IntegerField(blank=True, null=True, verbose_name='CUIT')),
                ('nombre_factura', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre')),
                ('domicilio_factura', models.CharField(blank=True, max_length=50, null=True, verbose_name='Domicilio')),
                ('movil_factura', models.CharField(blank=True, max_length=15, null=True, verbose_name='Móvil')),
                ('email_factura', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email*')),
                ('condicion_comprobante', models.IntegerField(choices=[(1, 'Contado'), (2, 'Cuenta Corriente')], default=1, verbose_name='Condición de Venta')),
                ('gravado', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=14, null=True, verbose_name='Gravado')),
                ('exento', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=14, null=True, verbose_name='Exento')),
                ('iva', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=14, null=True, verbose_name='IVA')),
                ('percep_ib', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=14, null=True, verbose_name='Percepción IB')),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=14, null=True, verbose_name='Total')),
                ('entrega', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=14, null=True, verbose_name='Entrega')),
                ('estado', models.CharField(blank=True, max_length=1, null=True, verbose_name='Estado')),
                ('marca', models.CharField(blank=True, max_length=1, null=True, verbose_name='Marca')),
                ('comision', models.CharField(blank=True, max_length=1, null=True, verbose_name='Comisión')),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='Fecha Pago')),
                ('no_estadist', models.BooleanField(blank=True, null=True, verbose_name='No estadist.')),
                ('suc_imp', models.SmallIntegerField(blank=True, null=True, verbose_name='sucimp')),
                ('cae', models.IntegerField(blank=True, default=0, null=True, verbose_name='CAE')),
                ('cae_vto', models.DateField(blank=True, null=True, verbose_name='Vcto. CAE')),
                ('observa_comprobante', models.CharField(blank=True, max_length=30, null=True, verbose_name='Observaciones')),
                ('stock_clie', models.BooleanField(blank=True, null=True, verbose_name='stockclie')),
                ('promo', models.BooleanField(blank=True, null=True, verbose_name='Promo')),
                ('id_cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.cliente', verbose_name='Cliente')),
                ('id_comprobante_venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.comprobanteventa', verbose_name='Comprobante')),
                ('id_deposito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.productodeposito', verbose_name='Depósito')),
                ('id_punto_venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.puntoventa', verbose_name='Punto de Venta')),
                ('id_sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.sucursal', verbose_name='Sucursal')),
                ('id_user', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('id_valida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.valida', verbose_name='Validar')),
                ('id_vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.vendedor', verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'db_table': 'factura',
            },
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('estacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fcontrol', models.CharField(blank=True, max_length=22, null=True)),
                ('id_detalle_factura', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.IntegerField(blank=True, null=True, verbose_name='Cód. Producto')),
                ('producto_venta', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre producto')),
                ('cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Cantidad')),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Costo')),
                ('precio_lista', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio')),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Descuento(%)')),
                ('desc_vendedor', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Descuento(%)')),
                ('gravado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Gravado')),
                ('alic_iva', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Alíc. IVA(%)')),
                ('iva', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='IVA')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Total')),
                ('reventa', models.CharField(blank=True, max_length=1, null=True, verbose_name='Reventa')),
                ('stock', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Stock')),
                ('act_stock', models.BooleanField(blank=True, null=True, verbose_name='Act. Stock')),
                ('id_operario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.operario')),
                ('id_producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.producto', verbose_name='Producto')),
                ('id_user', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('id_factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.factura', verbose_name='Factura')),
            ],
            options={
                'verbose_name': 'Detalle Factura',
                'verbose_name_plural': 'Detalles Factura',
                'db_table': 'detalle_factura',
            },
        ),
        migrations.CreateModel(
            name='SerialFactura',
            fields=[
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('estacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fcontrol', models.CharField(blank=True, max_length=22, null=True)),
                ('id_serial_factura', models.AutoField(primary_key=True, serialize=False)),
                ('producto_serial', models.CharField(blank=True, max_length=50, null=True, verbose_name='Serial producto')),
                ('id_factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.factura', verbose_name='Factura')),
                ('id_user', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Detalle Serial',
                'verbose_name_plural': 'Detalles Serial',
                'db_table': 'serial_factura',
            },
        ),
    ]
