# Generated by Django 5.1.1 on 2026-04-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockcliente',
            name='cantidad',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='stockcliente',
            name='retirado',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name='Retiro'),
        ),
    ]
