# Generated by Django 5.1.1 on 2025-09-16 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0005_alter_proveedor_codigo_postal_and_more'),
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('estacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fcontrol', models.CharField(blank=True, max_length=22, null=True)),
                ('id_comprovante', models.AutoField(primary_key=True, serialize=False)),
                ('estatus_comprabante', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estatus')),
                ('compro', models.CharField(blank=True, max_length=3, null=True, verbose_name='Compro')),
                ('letra_comprobante', models.CharField(blank=True, max_length=1, null=True, verbose_name='Letra')),
                ('numero_comprobante', models.IntegerField(blank=True, null=True, verbose_name='Número')),
                ('fecha_comprobante', models.DateField(blank=True, null=True, verbose_name='Fecha Emisión')),
                ('condicion_comprobante', models.IntegerField(choices=[(1, 'Contado'), (2, 'Cuenta Corriente')], default=1, verbose_name='Condición de Compra')),
                ('fecha_registro', models.DateField(blank=True, null=True, verbose_name='Fecha Registro')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha Vencimiento')),
                ('gravado', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=14, null=True, verbose_name='Gravado')),
                ('no_gravado', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=14, null=True, verbose_name='No Gravado')),
                ('no_inscripto', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=14, null=True, verbose_name='No Inscripto')),
                ('exento', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=14, null=True, verbose_name='Exento')),
                ('retencion_iva', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=14, null=True, verbose_name='Retención IVA')),
                ('retencion_ganancia', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=14, null=True, verbose_name='Retención Ganancia')),
                ('retencion_ingreso_bruto', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=14, null=True, verbose_name='Retención Ingreso Bruto')),
                ('sellado', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=14, null=True, verbose_name='Sellado')),
                ('percepcion_iva', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=14, null=True, verbose_name='Percepción IVA')),
                ('percepcion_ingreso_bruto', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=14, null=True, verbose_name='Percepción Ingreso Bruto')),
                ('iva', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=14, null=True, verbose_name='Iva')),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=14, null=True, verbose_name='Total')),
                ('entrega', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=14, null=True, verbose_name='Entrega')),
                ('documento_asociado', models.CharField(blank=True, default='', max_length=2, null=True, verbose_name='Documento Asociado')),
                ('alicuota_iva', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=14, null=True, verbose_name='Alicuota IVA')),
                ('observa_comprobante', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('id_comprobante_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.comprobanteventa', verbose_name='Comprobante')),
                ('id_deposito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.productodeposito', verbose_name='Depósito')),
                ('id_proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.proveedor', verbose_name='Proveedor')),
                ('id_provincia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.provincia', verbose_name='Provincia')),
                ('id_punto_venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.puntoventa', verbose_name='Punto de Venta')),
                ('id_sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.sucursal', verbose_name='Sucursal')),
                ('id_user', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'db_table': 'compra',
            },
        ),
    ]
