# Generated by Django 5.1.1 on 2026-01-21 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0002_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retencionrecibo',
            name='id_codigo_retencion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maestros.formapago', verbose_name='Código Retención'),
        ),
    ]
