# Generated by Django 5.1.1 on 2025-05-09 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='productos_camiones',
            field=models.BooleanField(blank=True, null=True, verbose_name='Productos de Camiones'),
        ),
        migrations.AddField(
            model_name='factura',
            name='recibo_manual_auto',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Talonario'),
        ),
        migrations.AddField(
            model_name='factura',
            name='suma_comision_vendedor',
            field=models.BooleanField(blank=True, null=True, verbose_name='Suma Comisión a Vendedor'),
        ),
    ]
