# Generated by Django 5.1.1 on 2026-01-05 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cajaarqueo',
            options={'verbose_name': 'Arqueo de Caja', 'verbose_name_plural': 'Arqueos de Caja'},
        ),
    ]
