# Generated by Django 5.1.1 on 2025-11-12 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0002_initial'),
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('estacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fcontrol', models.CharField(blank=True, max_length=22, null=True)),
                ('id_caja', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Caja')),
                ('estatus_caja', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estatus')),
                ('numero_caja', models.IntegerField(verbose_name='Número')),
                ('fecha_caja', models.DateField(verbose_name='Fecha')),
                ('saldoanterior', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Saldo Anterior')),
                ('ingresos', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Ingresos')),
                ('egresos', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Egresos')),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Saldo')),
                ('caja_cerrada', models.BooleanField(default=False, verbose_name='Cerrada')),
                ('recuento', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Recuento')),
                ('diferencia', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Diferencia')),
                ('hora_cierre', models.DateTimeField(verbose_name='Hora Cierre/Apertura')),
                ('observacion_caja', models.CharField(blank=True, max_length=50, null=True, verbose_name='Observaciones')),
                ('id_sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.sucursal', verbose_name='Sucursal')),
                ('id_user', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('id_usercierre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_cierre', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
                'db_table': 'caja',
            },
        ),
    ]
