# Generated by Django 5.1.1 on 2026-01-22 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0002_initial'),
        ('ventas', '0002_alter_retencionrecibo_id_codigo_retencion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retencionrecibo',
            name='id_codigo_retencion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maestros.codigoretencion', verbose_name='Código Retención'),
        ),
    ]
