# Generated by Django 5.1.1 on 2025-11-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_caja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='hora_cierre',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hora Cierre/Apertura'),
        ),
    ]
