# Generated by Django 5.1.1 on 2025-09-16 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0006_merge_20250916_1713'),
        ('ventas', '0002_compra'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='id_comprovante',
            new_name='id_compra',
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('estacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fcontrol', models.CharField(blank=True, max_length=22, null=True)),
                ('id_detalle_compra', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Cantidad')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Total')),
                ('despacho', models.CharField(blank=True, max_length=16, null=True, verbose_name='Despacho')),
                ('id_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.compra', verbose_name='Factura')),
                ('id_producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.producto', verbose_name='Producto')),
                ('id_user', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Detalle Compra',
                'verbose_name_plural': 'Detalles Compra',
                'db_table': 'detalle_compra',
            },
        ),
    ]
