# Generated by Django 5.1.1 on 2025-08-15 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_stockcliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockcliente',
            old_name='retiro',
            new_name='retirado',
        ),
    ]
