# Generated by Django 5.1.1 on 2025-05-15 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_chequerecibo_depositorecibo_detallerecibo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallerecibo',
            name='id_factura_cobrada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cobranza', to='ventas.factura', verbose_name='Factura Cobrada'),
        ),
        migrations.AlterField(
            model_name='detallerecibo',
            name='id_factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_recibo', to='ventas.factura', verbose_name='Factura'),
        ),
    ]
