# Generated by Django 5.1.1 on 2025-09-17 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_rename_id_comprovante_compra_id_compra_detallecompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompra',
            name='stock',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Stock'),
        ),
    ]
