# Generated by Django 5.1.1 on 2026-01-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_alter_retencionrecibo_id_codigo_retencion'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='compensa_factura',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=14, null=True, verbose_name='Compensa'),
        ),
    ]
