# Generated by Django 5.1.1 on 2025-11-25 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0003_formapago'),
        ('ventas', '0003_alter_caja_hora_cierre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CajaDetalle',
            fields=[
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('estacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fcontrol', models.CharField(blank=True, max_length=22, null=True)),
                ('id_caja_detalle', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Caja Detalle')),
                ('caja', models.PositiveIntegerField(db_index=True, help_text='Código de caja o sucursal')),
                ('idventas', models.SmallIntegerField(blank=True, null=True)),
                ('idcompras', models.SmallIntegerField(blank=True, null=True)),
                ('idbancos', models.SmallIntegerField(blank=True, null=True)),
                ('importe', models.DecimalField(decimal_places=2, help_text='Importe del movimiento (puede ser positivo o negativo)', max_digits=12)),
                ('observacion', models.CharField(blank=True, help_text='Observaciones del movimiento', max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('id_caja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ventas.caja', verbose_name='Caja Detalle')),
                ('id_forma_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.formapago', verbose_name='Forma de Pago')),
                ('id_user', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Detalle de Caja',
                'verbose_name_plural': 'Detalle de Cajas',
                'db_table': 'caja_detalle',
                'ordering': ['-fecha'],
            },
        ),
    ]
