# Generated by Django 5.1.1 on 2025-09-19 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0006_merge_20250916_1713'),
        ('ventas', '0004_detallecompra_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='id_comprobante_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.comprobantecompra', verbose_name='Comprobante'),
        ),
    ]
