# Generated by Django 5.1.1 on 2025-11-26 21:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_cajadetalle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cajadetalle',
            options={'ordering': ['-fecha_detalle_caja'], 'verbose_name': 'Detalle de Caja', 'verbose_name_plural': 'Detalle de Cajas'},
        ),
        migrations.RemoveField(
            model_name='cajadetalle',
            name='caja',
        ),
        migrations.RemoveField(
            model_name='cajadetalle',
            name='fecha',
        ),
        migrations.AddField(
            model_name='cajadetalle',
            name='fecha_detalle_caja',
            field=models.DateField(blank=True, default=django.utils.timezone.now, editable=False, null=True, verbose_name='Fecha Detalle'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='numero_caja',
            field=models.IntegerField(verbose_name='Número Caja'),
        ),
    ]
