# Generated by Django 5.1.1 on 2026-02-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_factura_compensa_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequerecibo',
            name='electronico',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Estatus'),
        ),
        migrations.AlterField(
            model_name='chequerecibo',
            name='importe_cheque',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name='Importe Cheque'),
        ),
        migrations.AlterField(
            model_name='depositorecibo',
            name='importe_deposito',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name='Importe Depósito'),
        ),
        migrations.AlterField(
            model_name='detallerecibo',
            name='monto_cobrado',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name='Costo'),
        ),
        migrations.AlterField(
            model_name='retencionrecibo',
            name='importe_retencion',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name='Importe Retención'),
        ),
        migrations.AlterField(
            model_name='tarjetarecibo',
            name='importe_tarjeta',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name='Importe Tarjeta'),
        ),
    ]
