# Generated by Django 5.1.1 on 2025-11-27 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_alter_cajadetalle_options_remove_cajadetalle_caja_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cajadetalle',
            options={'ordering': ['-id_caja'], 'verbose_name': 'Detalle de Caja', 'verbose_name_plural': 'Detalle de Cajas'},
        ),
        migrations.RemoveField(
            model_name='cajadetalle',
            name='fecha_detalle_caja',
        ),
    ]
