# Generated by Django 5.1.1 on 2026-02-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_alter_chequerecibo_electronico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallefactura',
            name='act_stock',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Act. Stock'),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='alic_iva',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True, verbose_name='Alíc. IVA(%)'),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='cantidad',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='costo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name='Costo'),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='desc_vendedor',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True, verbose_name='Descuento(%)'),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='descuento',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True, verbose_name='Descuento(%)'),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='gravado',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=14, null=True, verbose_name='Gravado'),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='iva',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=14, null=True, verbose_name='IVA'),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='precio_lista',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='stock',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=14, null=True, verbose_name='Total'),
        ),
    ]
