# Generated by Django 5.1.1 on 2025-09-19 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0006_merge_20250916_1713'),
        ('ventas', '0005_alter_compra_id_comprobante_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='id_comprobante_venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.comprobanteventa', verbose_name='Comprobante'),
        ),
    ]
