# Generated by Django 5.1.1 on 2025-11-27 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_alter_cajadetalle_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cajadetalle',
            name='tipo_movimiento',
            field=models.IntegerField(choices=[(1, 'Ingreso'), (2, 'Egreso')], default=1, verbose_name='Tipo de Movimiento'),
        ),
    ]
