# Generated by Django 5.1.1 on 2025-09-19 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0006_merge_20250916_1713'),
        ('ventas', '0006_compra_id_comprobante_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='id_comprobante_venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.comprobanteventa', verbose_name='Comp. origen Ret.'),
        ),
    ]
