# Generated by Django 5.1.1 on 2026-02-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_alter_detallefactura_act_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.CharField(blank=True, default='', max_length=1, null=True, verbose_name='Estado'),
        ),
    ]
