# Generated by Django 5.1.1 on 2025-12-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_cajadetalle_tipo_movimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='diferencia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Diferencia'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='egresos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Egresos'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='ingresos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ingresos'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='recuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Recuento'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saldo'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='saldoanterior',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saldo Anterior'),
        ),
    ]
