# Generated by Django 5.1.1 on 2026-03-10 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0011_alter_descuentorevendedor_unique_together_and_more'),
        ('ventas', '0007_alter_factura_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='id_marketing_origen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='maestros.marketingorigen', verbose_name='Marketing'),
        ),
    ]
