# Generated by Django 5.1.1 on 2025-09-19 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_compra_fecha_comprobante_venta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='numero_comprobante_venta',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número C/Comp.'),
        ),
    ]
