# Generated by Django 5.1.1 on 2026-03-18 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_factura_id_marketing_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefactura',
            name='desc_revendedor',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True, verbose_name='Desc. Rev(%)'),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='desc_vendedor',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True, verbose_name='Desc. Vend(%)'),
        ),
    ]
