# Generated by Django 5.1.1 on 2025-12-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_alter_caja_diferencia_alter_caja_egresos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='numero_caja',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número Caja'),
        ),
    ]
