# Generated by Django 5.1.1 on 2025-12-19 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0006_alter_detallevendedorcomision_id_vendedor_comision'),
        ('ventas', '0009_alter_caja_numero_caja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cajadetalle',
            name='importe',
            field=models.DecimalField(decimal_places=2, help_text='Importe del movimiento (puede ser positivo o negativo)', max_digits=12, verbose_name='Importe'),
        ),
        migrations.AlterField(
            model_name='cajadetalle',
            name='observacion',
            field=models.CharField(blank=True, help_text='Observaciones del movimiento', max_length=50, verbose_name='Observación'),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='id_operario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.operario', verbose_name='Operario'),
        ),
    ]
