# Generated by Django 5.1.1 on 2025-09-19 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0009_compra_numero_comprobante_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='total_comprobante_venta',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=14, null=True, verbose_name='Total C/Compra'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='numero_comprobante_venta',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número C/Compra'),
        ),
    ]
