# Generated by Django 5.1.1 on 2025-12-17 21:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0009_alter_caja_numero_caja'),
    ]

    operations = [
        migrations.CreateModel(
            name='CajaArqueo',
            fields=[
                ('id_caja_arqueo', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Caja Arqueo')),
                ('cantidad', models.DecimalField(blank=True, decimal_places=0, help_text='Cantidad de billetes/monedas', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, help_text='Valor de cada billete/moneda', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Unitario')),
                ('detalle', models.CharField(blank=True, help_text='Descripción del billete/moneda (ej: BILLETE 1000, MONEDA 100)', max_length=15, null=True, verbose_name='Detalle')),
                ('total', models.DecimalField(decimal_places=2, editable=False, help_text='Cantidad x Valor', max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total')),
                ('id_caja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ventas.caja', verbose_name='Caja')),
            ],
            options={
                'verbose_name': 'Arqueo de Caja',
                'verbose_name_plural': 'Arqueos de Caja',
                'db_table': 'caja_arqueo',
                'ordering': ['valor'],
            },
        ),
    ]
