# Generated by Django 5.1.1 on 2025-12-19 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0005_alter_descuentovendedor_id_marca_and_more'),
        ('ventas', '0010_cajaarqueo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CajaMedioPago',
            fields=[
                ('id_caja_medio_pago', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Caja Medio Pago')),
                ('idventas', models.SmallIntegerField(blank=True, null=True)),
                ('importe', models.DecimalField(decimal_places=2, help_text='Importe del movimiento (puede ser positivo o negativo)', max_digits=12)),
                ('id_caja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ventas.caja', verbose_name='Caja')),
                ('id_forma_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.formapago', verbose_name='Forma de Pago')),
            ],
            options={
                'verbose_name': 'Medio de pago de Caja',
                'verbose_name_plural': 'Medios de pago de Caja',
                'db_table': 'caja_medio_pago',
            },
        ),
    ]
