# Generated by Django 5.1.1 on 2025-12-19 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0010_alter_cajadetalle_importe_and_more'),
        ('ventas', '0011_cajamediopago'),
    ]

    operations = [
    ]
