# Generated by Django 5.1.1 on 2025-09-29 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0011_alter_compra_alicuota_iva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='alicuota_iva',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4, null=True, verbose_name='Alicuota'),
        ),
    ]
