# Generated by Django 5.1.1 on 2025-10-01 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0012_alter_compra_alicuota_iva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='fecha_comprobante_venta',
        ),
    ]
