# Generated by Django 5.1.1 on 2025-12-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0012_merge_20251219_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cajadetalle',
            name='importe',
            field=models.DecimalField(decimal_places=2, help_text='Importe del movimiento (puede ser positivo o negativo)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='cajadetalle',
            name='observacion',
            field=models.CharField(blank=True, help_text='Observaciones del movimiento', max_length=50),
        ),
    ]
