# Generated by Django 5.1.1 on 2025-12-23 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0013_alter_cajadetalle_importe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chequerecibo',
            name='electronico',
            field=models.BooleanField(blank=True, null=True, verbose_name='Estatus'),
        ),
        migrations.AddField(
            model_name='factura',
            name='id_caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ventas.caja', verbose_name='Caja'),
        ),
    ]
