# Generated by Django 5.1.1 on 2025-11-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='order',
            field=models.IntegerField(blank=True, default=0, verbose_name='Orden de aparición'),
        ),
    ]
