# Generated by Django 5.1.1 on 2026-04-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobantecompra',
            name='nombre_impresion',
            field=models.CharField(blank=True, choices=[('FACTURA', 'FACTURA'), ('NOTA DE CRÉDITO', 'NOTA DE CRÉDITO'), ('NOTA DE DÉBITO', 'NOTA DE DÉBITO'), ('ORDEN DE PAGO', 'ORDEN DE PAGO'), ('AJUSTE', 'AJUSTE'), ('RETENCIÓN', 'RETENCIÓN'), ('REMITOS', 'REMITO'), ('DEVOLUCIÓN', 'DEVOLUCIÓN')], max_length=20, null=True, verbose_name='Nombre Impresión'),
        ),
    ]
