# Generated by Django 5.1.1 on 2025-05-13 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('estacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fcontrol', models.CharField(blank=True, max_length=22, null=True)),
                ('id_banco', models.AutoField(primary_key=True, serialize=False)),
                ('cuenta_banco', models.IntegerField(blank=True, null=True)),
                ('nombre_banco', models.CharField(max_length=30)),
                ('numero_cuenta', models.CharField(max_length=15)),
                ('cbu', models.CharField(max_length=22)),
                ('codbco', models.IntegerField()),
                ('sucursal', models.IntegerField()),
                ('localidad', models.IntegerField()),
                ('imputacion', models.IntegerField()),
                ('cut', models.IntegerField()),
                ('tope', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reporte', models.CharField(max_length=20)),
                ('provedor', models.IntegerField()),
                ('moneda', models.IntegerField()),
                ('id_user', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
                'db_table': 'banco',
                'ordering': ['nombre_banco'],
            },
        ),
        migrations.CreateModel(
            name='CodigoRetencion',
            fields=[
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('estacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fcontrol', models.CharField(blank=True, max_length=22, null=True)),
                ('id_codigo_retencion', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nombre_codigo_retencion', models.CharField(max_length=30)),
                ('imputacion', models.IntegerField()),
                ('id_user', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Codigo Retención',
                'verbose_name_plural': 'Codigos Retención',
                'db_table': 'codigo_retencion',
                'ordering': ['nombre_codigo_retencion'],
            },
        ),
        migrations.CreateModel(
            name='ConceptoBanco',
            fields=[
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('estacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fcontrol', models.CharField(blank=True, max_length=22, null=True)),
                ('id_concepto_banco', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_concepto_banco', models.CharField(max_length=30, verbose_name='Descripción')),
                ('factor', models.IntegerField(verbose_name='Factor')),
                ('id_user', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Concepto Bancario',
                'verbose_name_plural': 'Conceptos Bancarios',
                'db_table': 'cptobco',
                'ordering': ['nombre_concepto_banco'],
            },
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('estacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fcontrol', models.CharField(blank=True, max_length=22, null=True)),
                ('id_tarjeta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tarjeta', models.CharField(max_length=30)),
                ('imputation', models.IntegerField()),
                ('banco_acreditacion', models.IntegerField()),
                ('propia', models.BooleanField()),
                ('id_user', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Tarjeta',
                'verbose_name_plural': 'Tarjetas',
                'db_table': 'tarjeta',
                'ordering': ['nombre_tarjeta'],
            },
        ),
    ]
