# Generated by Django 5.1.1 on 2024-11-04 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0002_remove_comprobanteventa_impresion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localidad',
            options={'ordering': ['id_provincia', 'nombre_localidad'], 'verbose_name': 'Localidad', 'verbose_name_plural': 'Localidades'},
        ),
        migrations.AddField(
            model_name='proveedor',
            name='id_provincia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='maestros.provincia', verbose_name='Provincia*'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='codigo_postal',
            field=models.CharField(max_length=5, verbose_name='Código Postal*'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='id_localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestros.localidad', verbose_name='Localidad*'),
        ),
    ]
