# Generated by Django 5.1.1 on 2025-09-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobanteventa',
            name='mipyme',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='MiPyME'),
        ),
    ]
