# Generated by Django 5.1.1 on 2024-09-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0002_alter_cliente_codigo_postal'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='fecha_registro_actividad',
            field=models.DateField(blank=True, null=True),
        ),
    ]
