# Generated by Django 5.1.1 on 2025-11-25 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('estacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fcontrol', models.CharField(blank=True, max_length=22, null=True)),
                ('id_forma_pago', models.AutoField(primary_key=True, serialize=False)),
                ('estatus_forma_pago', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estatus')),
                ('descripcion_forma_pago', models.CharField(max_length=20, verbose_name='Forma Pago')),
                ('id_user', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Forma de Pago',
                'verbose_name_plural': 'Formas de Pago',
                'db_table': 'forma_pago',
                'ordering': ['descripcion_forma_pago'],
            },
        ),
    ]
