# Generated by Django 5.1.1 on 2025-08-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='iva_exento',
            field=models.BooleanField(default=False, verbose_name='IVA Exento'),
        ),
        migrations.AddField(
            model_name='producto',
            name='obliga_operario',
            field=models.BooleanField(default=False, verbose_name='Carrito'),
        ),
    ]
