# Generated by Django 5.1.1 on 2025-09-08 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobanteventa',
            name='interno',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Interno'),
        ),
    ]
