# Generated by Django 5.1.1 on 2026-02-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banco',
            name='codigo_banco',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Código Banco'),
        ),
        migrations.AlterField(
            model_name='banco',
            name='cuit_banco',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='CUIT'),
        ),
        migrations.AlterField(
            model_name='cuentabanco',
            name='codigo_imputacion',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Cód. Imputación'),
        ),
        migrations.AlterField(
            model_name='cuentabanco',
            name='codigo_postal',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Código Postal'),
        ),
        migrations.AlterField(
            model_name='cuentabanco',
            name='sucursal',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Sucursal'),
        ),
        migrations.AlterField(
            model_name='cuentabanco',
            name='tipo_cuenta',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Caja de Ahorros'), (2, 'Cuenta Corriente'), (3, 'Mcdo/Pago Transferencia')], default=0, null=True, verbose_name='Tipo de Cta.'),
        ),
        migrations.AlterField(
            model_name='mediopago',
            name='plazo_medio_pago',
            field=models.IntegerField(default=0, verbose_name='Plazo medio de Pago'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='imputacion',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Cód. Imputación'),
        ),
    ]
