# Generated by Django 5.1.1 on 2026-02-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0003_alter_banco_codigo_banco_alter_banco_cuit_banco_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='ws_archivo_crt',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='ws_archivo_key',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='ws_expiracion',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='ws_sign',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='ws_token',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='ws_vence',
        ),
        migrations.AddField(
            model_name='empresa',
            name='ws_archivo_crt_p',
            field=models.TextField(blank=True, null=True, verbose_name='CRT Producción'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='ws_archivo_key_p',
            field=models.TextField(blank=True, null=True, verbose_name='KEY Producción'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='ws_expiracion_h',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiración Ticket WS H'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='ws_expiracion_p',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiración Ticket WS P'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='ws_sign_h',
            field=models.TextField(blank=True, null=True, verbose_name='Sign Homologación'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='ws_sign_p',
            field=models.TextField(blank=True, null=True, verbose_name='Sign Producción'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='ws_token_h',
            field=models.TextField(blank=True, null=True, verbose_name='Token Homologación'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='ws_token_p',
            field=models.TextField(blank=True, null=True, verbose_name='Token Producción'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='ws_vence_h',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Vcto. Certificado H*'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='ws_vence_p',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Vcto. Certificado P*'),
        ),
    ]
