# Generated by Django 5.1.1 on 2025-12-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0003_formapago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediopago',
            name='nombre_medio_pago',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
    ]
