# Generated by Django 5.1.1 on 2025-09-09 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0003_comprobanteventa_interno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='black_list',
            field=models.BooleanField(choices=[(True, 'SI'), (False, 'NO')], default=False, verbose_name='Black List'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cliente_empresa',
            field=models.BooleanField(blank=True, choices=[(True, 'SI'), (False, 'NO')], default=False, null=True, verbose_name='Cliente Empresa'),
        ),
    ]
