# Generated by Django 5.1.1 on 2025-09-03 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0003_alter_comprobanteventa_mipyme'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cliente_empresa',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Cliente Empresa'),
        ),
    ]
