# Generated by Django 5.1.1 on 2025-05-13 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0003_banco_codigoretencion_conceptobanco_tarjeta'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='conceptobanco',
            table='concepto_banco',
        ),
    ]
