# Generated by Django 5.1.1 on 2025-08-14 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0003_producto_iva_exento_producto_obliga_operario'),
        ('ventas', '0002_detallefactura_no_gravado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='obliga_operario',
            field=models.BooleanField(default=False, verbose_name='Obliga Operario'),
        ),
        migrations.CreateModel(
            name='StockCliente',
            fields=[
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('estacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fcontrol', models.CharField(blank=True, max_length=22, null=True)),
                ('id_stock_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Cantidad')),
                ('retiro', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Retiro')),
                ('fecha_retiro', models.DateField(blank=True, null=True, verbose_name='Fecha Retiro')),
                ('numero', models.IntegerField(blank=True, null=True, verbose_name='Número')),
                ('comentario', models.CharField(blank=True, max_length=50, null=True, verbose_name='Comentario')),
                ('id_factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ventas.factura', verbose_name='Factura')),
                ('id_producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.producto', verbose_name='Producto')),
                ('id_user', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Stock Cliente',
                'verbose_name_plural': 'Stocks Clientes',
                'db_table': 'stock_cliente',
                'ordering': ['id_stock_cliente'],
            },
        ),
    ]
