# Generated by Django 5.1.1 on 2025-05-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0004_alter_conceptobanco_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobanteventa',
            name='recibo',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Recibo'),
        ),
    ]
