# Generated by Django 5.1.1 on 2026-02-12 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0004_remove_empresa_ws_archivo_crt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='ws_archivo_crt2',
            field=models.TextField(blank=True, null=True, verbose_name='CRT Homologación'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='ws_archivo_key2',
            field=models.TextField(blank=True, null=True, verbose_name='KEY Homologación'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='ws_vence_h',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Vcto. Certificado H'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='ws_vence_p',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Vcto. Certificado P'),
        ),
    ]
