# Generated by Django 5.1.1 on 2025-09-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0004_alter_cliente_black_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Stock'),
        ),
    ]
