# Generated by Django 5.1.1 on 2025-09-15 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0004_alter_cliente_black_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Código Postal*'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='domicilio_proveedor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Domicilio'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='email_proveedor',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='ib_alicuota',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4, null=True, verbose_name='Alíc. Ing. B.'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='ib_exento',
            field=models.BooleanField(blank=True, null=True, verbose_name='Exento Ret. Ing. Bruto'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='ib_numero',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Ingreso Bruto*'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='id_localidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.localidad', verbose_name='Localidad*'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='id_provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.provincia', verbose_name='Provincia*'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='id_tipo_iva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.tipoiva', verbose_name='Tipo IVA'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='id_tipo_retencion_ib',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.tiporetencionib', verbose_name='Tipo de Retención Ib'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='multilateral',
            field=models.BooleanField(blank=True, null=True, verbose_name='Contrib. Conv. Multilateral'),
        ),
    ]
