# Generated by Django 5.1.1 on 2024-11-04 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0004_actividad_id_user_cliente_id_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localidad',
            options={'ordering': ['codigo_postal'], 'verbose_name': 'Localidad', 'verbose_name_plural': 'Localidades'},
        ),
        migrations.RemoveField(
            model_name='productominimo',
            name='cai',
        ),
        migrations.RemoveField(
            model_name='productominimo',
            name='id_producto',
        ),
        migrations.AlterField(
            model_name='mediopago',
            name='plazo_medio_pago',
            field=models.IntegerField(verbose_name='Plazo medio de Pago'),
        ),
        migrations.CreateModel(
            name='ProductoCai',
            fields=[
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('estacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fcontrol', models.CharField(blank=True, max_length=22, null=True)),
                ('id_cai', models.AutoField(primary_key=True, serialize=False)),
                ('estatus_cai', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estatus*')),
                ('cai', models.CharField(max_length=20, verbose_name='CAI*')),
                ('descripcion_cai', models.CharField(blank=True, max_length=50, null=True, verbose_name='Descripción CAI')),
                ('id_user', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'CAI',
                'verbose_name_plural': 'CAIs de Productos',
                'db_table': 'producto_cai',
                'ordering': ['cai'],
            },
        ),
        migrations.AddField(
            model_name='productominimo',
            name='id_cai',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='maestros.productocai', verbose_name='CAI'),
            preserve_default=False,
        ),
    ]
