# Generated by Django 5.1.1 on 2025-08-14 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0004_alter_producto_obliga_operario_stockcliente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockCliente',
        ),
    ]
