# Generated by Django 5.1.1 on 2025-12-17 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0004_alter_mediopago_nombre_medio_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descuentovendedor',
            name='id_marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestros.productomarca', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono_proveedor',
            field=models.CharField(max_length=15, verbose_name='Teléfono'),
        ),
    ]
