# Generated by Django 5.1.1 on 2025-12-19 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0005_alter_descuentovendedor_id_marca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallevendedorcomision',
            name='id_vendedor_comision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.vendedorcomision', verbose_name='Vendedor Comisión'),
        ),
    ]
