# Generated by Django 5.1.1 on 2024-10-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0005_remove_cliente_id_usuario_cliente_id_provincia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo_persona',
            field=models.CharField(choices=[('N', 'Natural'), ('F', 'Física')], default='N', max_length=1, verbose_name='Tipo de Persona'),
        ),
    ]
