# Generated by Django 5.1.1 on 2025-05-27 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0005_comprobanteventa_recibo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banco',
            name='codbco',
        ),
        migrations.RemoveField(
            model_name='banco',
            name='cut',
        ),
        migrations.RemoveField(
            model_name='banco',
            name='localidad',
        ),
        migrations.RemoveField(
            model_name='banco',
            name='moneda',
        ),
        migrations.RemoveField(
            model_name='banco',
            name='provedor',
        ),
        migrations.AddField(
            model_name='banco',
            name='cod_bco',
            field=models.IntegerField(blank=True, null=True, verbose_name='Código Banco'),
        ),
        migrations.AddField(
            model_name='banco',
            name='codigo_postal',
            field=models.IntegerField(blank=True, null=True, verbose_name='Código Postal'),
        ),
        migrations.AddField(
            model_name='banco',
            name='cuit',
            field=models.IntegerField(blank=True, null=True, verbose_name='CUIT'),
        ),
        migrations.AddField(
            model_name='banco',
            name='estatus_banco',
            field=models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estatus'),
        ),
        migrations.AddField(
            model_name='banco',
            name='id_moneda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.moneda', verbose_name='Moneda'),
        ),
        migrations.AddField(
            model_name='banco',
            name='id_proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='banco',
            name='cbu',
            field=models.CharField(blank=True, max_length=22, null=True, verbose_name='CBU'),
        ),
        migrations.AlterField(
            model_name='banco',
            name='cuenta_banco',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cuenta Banco'),
        ),
        migrations.AlterField(
            model_name='banco',
            name='imputacion',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cód. Imputación'),
        ),
        migrations.AlterField(
            model_name='banco',
            name='nombre_banco',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre Banco'),
        ),
        migrations.AlterField(
            model_name='banco',
            name='numero_cuenta',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Número Cuenta'),
        ),
        migrations.AlterField(
            model_name='banco',
            name='reporte',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Reporte'),
        ),
        migrations.AlterField(
            model_name='banco',
            name='sucursal',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sucursal'),
        ),
        migrations.AlterField(
            model_name='banco',
            name='tope',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name='Tope'),
        ),
    ]
