# Generated by Django 5.1.1 on 2025-08-21 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0005_delete_stockcliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoiva',
            name='codigo_afip_responsable',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Cód. AFIP'),
        ),
    ]
