# Generated by Django 5.1.1 on 2026-02-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0005_alter_empresa_ws_archivo_crt2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobanteventa',
            name='tipo_numeracion',
            field=models.IntegerField(blank=True, choices=[(1, 'Manual'), (2, 'Automática Sistema'), (3, 'Automática ARCA')], null=True, verbose_name='Tipo Numeración'),
        ),
        migrations.AlterField(
            model_name='comprobanteventa',
            name='compro_asociado',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Comprobante Asociado'),
        ),
    ]
