# Generated by Django 5.1.1 on 2025-09-16 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0005_alter_producto_stock'),
        ('maestros', '0005_alter_proveedor_codigo_postal_and_more'),
    ]

    operations = [
    ]
