# Generated by Django 5.1.1 on 2024-11-04 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0005_alter_localidad_options_remove_productominimo_cai_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='cai',
        ),
    ]
