# Generated by Django 5.1.1 on 2025-05-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0006_remove_banco_codbco_remove_banco_cut_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarjeta',
            name='imputation',
        ),
        migrations.AddField(
            model_name='codigoretencion',
            name='estatus_cod_retencion',
            field=models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estatus'),
        ),
        migrations.AddField(
            model_name='conceptobanco',
            name='estatus_concepto_banco',
            field=models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estatus'),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='estatus_tarjeta',
            field=models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estatus'),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='imputacion',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cód. Imputación'),
        ),
        migrations.AlterField(
            model_name='codigoretencion',
            name='imputacion',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cód. Imputación'),
        ),
        migrations.AlterField(
            model_name='codigoretencion',
            name='nombre_codigo_retencion',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre Cód. Ret.'),
        ),
        migrations.AlterField(
            model_name='conceptobanco',
            name='nombre_concepto_banco',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='banco_acreditacion',
            field=models.IntegerField(blank=True, null=True, verbose_name='Banco'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='nombre_tarjeta',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre Tarjeta'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='propia',
            field=models.BooleanField(default=False, verbose_name='Propia'),
        ),
    ]
