# Generated by Django 5.1.1 on 2025-08-21 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0006_tipoiva_codigo_afip_responsable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoiva',
            name='codigo_afip_responsable',
            field=models.IntegerField(blank=True, default=0, null=True, unique=True, verbose_name='Cód. AFIP'),
        ),
    ]
