# Generated by Django 5.1.1 on 2026-03-02 22:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0006_comprobanteventa_tipo_numeracion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DescuentoRevendedor',
            fields=[
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('estacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fcontrol', models.CharField(blank=True, max_length=22, null=True)),
                ('id_descuento_revendedor', models.AutoField(primary_key=True, serialize=False)),
                ('estatus_descuento_revendedor', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estatus')),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(99.99)], verbose_name='Descuento')),
                ('id_familia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestros.productofamilia', verbose_name='Familia')),
                ('id_marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestros.productomarca', verbose_name='Marca')),
                ('id_user', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Descuento Revendedor',
                'verbose_name_plural': 'Descuentos Revendedores',
                'db_table': 'descuento_revendedor',
                'ordering': ['id_marca', 'id_familia'],
            },
        ),
    ]
