# Generated by Django 5.1.1 on 2024-11-04 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0006_remove_producto_cai'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='id_cai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.productocai', verbose_name='CAI'),
        ),
    ]
