# Generated by Django 5.1.1 on 2025-09-24 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0006_merge_20250916_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobantecompra',
            name='remito',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Remito'),
        ),
        migrations.AddField(
            model_name='comprobantecompra',
            name='retencion',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Retención'),
        ),
    ]
