# Generated by Django 5.1.1 on 2025-09-30 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0007_comprobantecompra_remito_comprobantecompra_retencion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='carrito',
            field=models.BooleanField(default=False, verbose_name='Carrito'),
        ),
    ]
