# Generated by Django 5.1.1 on 2026-03-02 22:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0007_descuentorevendedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descuentorevendedor',
            name='descuento',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(99.99)], verbose_name='Descuento'),
        ),
    ]
