# Generated by Django 5.1.1 on 2025-05-28 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0007_remove_tarjeta_imputation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigoretencion',
            name='id_codigo_retencion',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='conceptobanco',
            name='id_concepto_banco',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
