# Generated by Django 5.1.1 on 2024-11-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0007_producto_id_cai'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='codigo_postal',
            field=models.CharField(default=1, max_length=5, verbose_name='Código Postal*'),
            preserve_default=False,
        ),
    ]
