# Generated by Django 5.1.1 on 2025-08-22 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0007_alter_tipoiva_codigo_afip_responsable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedidasEstados',
            fields=[
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('estacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fcontrol', models.CharField(blank=True, max_length=22, null=True)),
                ('id_medida_estado', models.AutoField(primary_key=True, serialize=False)),
                ('estatus_medida_estado', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estatus')),
                ('stock_desde', models.IntegerField(blank=True, default=0, null=True, verbose_name='Desde Stock')),
                ('stock_hasta', models.IntegerField(blank=True, default=0, null=True, verbose_name='Hasta Stock')),
                ('id_cai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.productocai', verbose_name='Moneda')),
                ('id_estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.productoestado', verbose_name='Estado')),
                ('id_user', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Estado por Medida',
                'verbose_name_plural': 'Estados por Medidas',
                'db_table': 'medidas_estados',
            },
        ),
    ]
