# Generated by Django 5.1.1 on 2025-05-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0008_alter_codigoretencion_id_codigo_retencion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigoretencion',
            name='imputacion',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Cód. Imputación'),
        ),
    ]
