# Generated by Django 5.1.1 on 2025-10-01 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0008_alter_producto_carrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobantecompra',
            name='libro_iva',
            field=models.BooleanField(default=False, verbose_name='Libro IVA'),
        ),
    ]
