# Generated by Django 5.1.1 on 2025-08-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0008_medidasestados'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='ws_archivo_crt2',
            field=models.TextField(blank=True, null=True, verbose_name='Token'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='ws_archivo_key2',
            field=models.TextField(blank=True, null=True, verbose_name='Sign'),
        ),
    ]
