# Generated by Django 5.1.1 on 2026-03-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0008_alter_descuentorevendedor_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descuentorevendedor',
            name='descuento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Descuento'),
        ),
    ]
