# Generated by Django 5.1.1 on 2024-11-07 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0008_sucursal_codigo_postal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo_producto',
            field=models.CharField(choices=[('P', 'Producto'), ('S', 'Servicio')], max_length=1, verbose_name='Tipo producto'),
        ),
        migrations.CreateModel(
            name='PuntoVenta',
            fields=[
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('estacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fcontrol', models.CharField(blank=True, max_length=22, null=True)),
                ('id_punto_venta', models.AutoField(primary_key=True, serialize=False)),
                ('estatus_punto_venta', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estatus')),
                ('punto_venta', models.CharField(max_length=5, verbose_name='Punto de Venta')),
                ('descripcion_punto_venta', models.CharField(blank=True, max_length=50, null=True, verbose_name='Descripción Pto. Venta')),
                ('id_user', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Punto de Venta',
                'verbose_name_plural': 'Puntos de Venta',
                'db_table': 'punto_venta',
                'ordering': ['punto_venta'],
            },
        ),
    ]
