# Generated by Django 5.1.1 on 2026-03-04 15:54

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0009_alter_descuentorevendedor_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descuentorevendedor',
            name='descuento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('99.99'))], verbose_name='Descuento'),
        ),
    ]
