# Generated by Django 5.1.1 on 2025-08-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0009_empresa_ws_archivo_crt2_empresa_ws_archivo_key2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='ws_archivo_crt2',
            field=models.TextField(blank=True, null=True, verbose_name='CRT'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='ws_archivo_key2',
            field=models.TextField(blank=True, null=True, verbose_name='KEY'),
        ),
    ]
