# Generated by Django 5.1.1 on 2024-10-03 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0006_remove_parametro_bonificacion_and_more'),
        ('maestros', '0009_alter_cliente_mayorista'),
    ]

    operations = [
    ]
