# Generated by Django 5.1.1 on 2025-08-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0010_alter_empresa_ws_archivo_crt2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoestado',
            name='color',
            field=models.CharField(blank=True, default='#FFFFFF', help_text='Código de color en formato hexadecimal (ej: #FFFFFF)', max_length=7),
        ),
    ]
