# Generated by Django 5.1.1 on 2026-03-09 21:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0010_alter_descuentorevendedor_descuento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='descuentorevendedor',
            unique_together={('id_marca', 'id_familia')},
        ),
        migrations.AlterUniqueTogether(
            name='descuentovendedor',
            unique_together={('id_marca', 'id_familia')},
        ),
        migrations.AddConstraint(
            model_name='descuentorevendedor',
            constraint=models.UniqueConstraint(fields=('id_marca', 'id_familia'), name='unique_marca_familia_revendedor', violation_error_message='Ya existe una configuración de descuento para esta combinación de Marca y Familia.'),
        ),
        migrations.AddConstraint(
            model_name='descuentovendedor',
            constraint=models.UniqueConstraint(fields=('id_marca', 'id_familia'), name='unique_marca_familia_vendedor', violation_error_message='Ya existe una configuración de descuento para esta combinación de Marca y Familia.'),
        ),
    ]
