# Generated by Django 5.1.1 on 2025-08-27 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0010_alter_empresa_ws_archivo_crt2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobanteventa',
            name='manual',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Manual'),
        ),
    ]
