# Generated by Django 5.1.1 on 2025-08-26 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0011_productoestado_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='id_producto_estado',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.productoestado', verbose_name='Estado'),
        ),
    ]
