# Generated by Django 5.1.1 on 2026-03-18 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0011_alter_descuentorevendedor_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medidasestados',
            options={'verbose_name': 'Estado por CAI', 'verbose_name_plural': 'Estados por CAI'},
        ),
    ]
