# Generated by Django 5.1.1 on 2025-08-27 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0011_comprobanteventa_manual'),
        ('maestros', '0012_producto_id_producto_estado'),
    ]

    operations = [
    ]
