# Generated by Django 5.1.1 on 2026-03-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0012_alter_medidasestados_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='logo_empresa',
            field=models.BinaryField(blank=True, null=True, verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='ws_expiracion_h',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Exp. Ticket WS H'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='ws_expiracion_p',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Exp. Ticket WS P'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='ws_vence_h',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Vcto. Cert. H'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='ws_vence_p',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Vcto. Certi. P'),
        ),
    ]
