# Generated by Django 5.1.1 on 2026-03-23 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0013_alter_empresa_logo_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='ws_vence_h',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Vcto. CRT. H.'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='ws_vence_p',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Vcto. Cert. P.'),
        ),
    ]
