# Generated by Django 5.1.1 on 2025-08-29 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0013_merge_20250827_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medidasestados',
            name='id_cai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.productocai', verbose_name='CAI'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cai',
            field=models.CharField(blank=True, max_length=21, null=True, verbose_name='CAI.'),
        ),
    ]
