# Generated by Django 5.1.1 on 2026-03-24 21:31

import apps.maestros.models.empresa_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0014_alter_empresa_ws_vence_h_alter_empresa_ws_vence_p'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='logo_empresa',
            field=models.ImageField(blank=True, help_text='Formatos permitidos: JPG, PNG, GIF. Tamaño máximo: 2MB', max_length=255, null=True, upload_to=apps.maestros.models.empresa_models.logo_upload_path, verbose_name='Logo'),
        ),
    ]
