# Generated by Django 5.1.1 on 2025-08-29 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0014_alter_medidasestados_id_cai_alter_producto_cai'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobanteventa',
            name='mipyme',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Manual'),
        ),
    ]
