# Generated by Django 5.1.1 on 2025-08-29 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0015_comprobanteventa_mipyme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobanteventa',
            name='mipyme',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='MYPIME'),
        ),
    ]
