# Generated by Django 5.1.1 on 2025-09-01 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0016_alter_comprobanteventa_mipyme'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobanteventa',
            name='ncr_nbd',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='NCR_NDB'),
        ),
    ]
