# Generated by Django 5.1.1 on 2025-09-01 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0017_comprobanteventa_ncr_nbd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comprobanteventa',
            old_name='ncr_nbd',
            new_name='ncr_ndb',
        ),
    ]
