# Generated by Django 5.1.1 on 2025-09-01 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0018_rename_ncr_nbd_comprobanteventa_ncr_ndb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobanteventa',
            name='ncr_ndb',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='NCR/NDB'),
        ),
    ]
