# Generated by Django 5.1.1 on 2024-11-08 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0009_alter_producto_tipo_producto_puntoventa'),
        ('usuarios', '0002_remove_user_vendedor_user_id_sucursal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='punto_venta',
        ),
        migrations.AddField(
            model_name='user',
            name='id_punto_venta',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.puntoventa'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestros.sucursal', verbose_name='Sucursal'),
        ),
    ]
