# Generated by Django 5.1.1 on 2024-11-08 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0009_alter_producto_tipo_producto_puntoventa'),
        ('usuarios', '0003_remove_user_punto_venta_user_id_punto_venta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_punto_venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestros.puntoventa'),
        ),
    ]
